### ISSUE TITLE
Issues with installation instructions

### ISSUE THREAD

**Issue by ghost** [opensolutions/ViMbAdmin#102]
Just a few things I noticed that are wrong with the installation instructions:

1. In dovecot-sql.conf.ext, "Mailbox" was erroneously capitalized.
2. The password_query was completely wrong. It should be:
```
password_query = SELECT username as user, password as password, \
        homedir AS userdb_home, maildir AS userdb_mail, \
        concat('*:bytes=', quota) AS userdb_quota_rule, uid AS userdb_uid, gid AS userdb_gid \
    FROM mailbox \
        WHERE username = '%Lu' AND active = '1' \
            AND ( access_restriction = 'ALL' OR LOCATE( '%Us', access_restriction ) > 0 )
```
Also, in `/etc/dovecot/conf.d/10-auth.conf`, `auth_mechanisms` should be set accordingly:
```
auth_mechanisms = plain login
```
I banged my head for an hour wondering why not MD5 nor SHA512 would work. I tried `crypt:md5`, `md5.salted`, nothing worked. Not till I changed `auth_mechanisms` to `plain login` and removed the others suggested in the configuration instructions. Now MD5 and even SHA512 work great.

**Comment by barryo** [comment]
All updated, thanks.
