### ISSUE TITLE
Why .htaccess necessory?

### ISSUE THREAD

**Issue by MiteshShah** [opensolutions/ViMbAdmin#108]
I've nginx server and nginx doesn't support .htaccess rules

``` bash
root@easyengine:/var/www/22222/htdocs/vimbadmin# ./bin/doctrine2-cli.php orm:schema-tool:create
ERROR: public/.htaccess does not exist / is not readable - set this up first!
```

Ref: https://github.com/opensolutions/ViMbAdmin/blob/0211c334b4b3168ab42fedb18bcba74e906ccf3f/bin/utils.inc#L62

**Comment by ariq01** [comment]
i want to install vimbadmin too, and stucked on same problem.
followed by this guide : https://easyengine.io/tutorials/mail/server/postfix-dovecot-ubuntu/

please help, thanks

**Comment by barryo** [comment]
It's not necessary as shown in the official installation documentation:

https://github.com/opensolutions/ViMbAdmin/wiki/Installation
