### ISSUE TITLE
Unreasonable Password Length

### ISSUE THREAD

**Issue by vogan** [opensolutions/ViMbAdmin#112]
Users on our mailserver want to set passwords which are longer than 32 characters. I don't get why this limitation exists, it's completely useless as passwords are stored as hashes.

Please consider my changes:
https://github.com/vogan/ViMbAdmin/commit/da1dfbcdeb6ab280fa1e597307265c51cc7799df

Thank you very much!

**Comment by barryo** [comment]
@vogan - can you open a pull request for this?

**Comment by vogan** [comment]
created pull request, issue #123

**Comment by barryo** [comment]
Closed via #123
