### ISSUE TITLE
orm:schema-tool:create only creates domain_admins 

### ISSUE THREAD

**Issue by petershaw** [opensolutions/ViMbAdmin#124]
Hi, 
i run ./bin/doctrine2-cli.php orm:schema-tool:create, but only one table is created. 
The Webinterfaice failes with:

```
File
/usr/local/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line
103
Message
An exception occurred while executing 'SELECT COUNT(a0_.id) AS sclr_0 FROM admin.admin a0_': SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'vimbadmin'@'localhost' for table 'admin'
Code
0
```

I am using debian, with php PHP 5.4.36-0+deb7u3 

Validate seems to be ok:

```
root@c4ba9180f503:/usr/local/vimbadmin# bin/doctrine2-cli.php orm:validate-schema
[Mapping]  OK - The mapping files are correct.
[Database] OK - The database schema is in sync with the mapping files.
```

But this is my schema:

```
mysql> show tables;
+---------------------+
| Tables_in_vimbadmin |
+---------------------+
| domain_admins       |
+---------------------+
1 row in set (0.00 sec)
```

How to install necessary tables?

**Comment by ACCBizon** [comment]
yah, i have the same problem :/

**Comment by petershaw** [comment]
Thank you very much.

**Comment by barryo** [comment]
:smile:

**Comment by feaber** [comment]
I still have same error.
Does this fix 6bef0bbaec8ec68bab24ae251c304824f8869429 work for You?

**Comment by feaber** [comment]
Ok, so the database __have to__ be named 'vimbadmin'.
If You use other db name, You will end up with error described by petershaw.

Not sure but still looks like issue here.

**Comment by barryo** [comment]
> Ok, so the database have to be named 'vimbadmin'.

It probably didn't until this fix. Reopening to allow for differently named databases when I have a chance.

**Comment by barryo** [comment]
[Comment](https://github.com/opensolutions/ViMbAdmin/wiki/Installation#database-setup) added to installation instructions also.

**Comment by eXistenZNL** [comment]
The problem is that every Doctrine schema XML has schema="vimbadmin" in the entity element.

A quick workaround is:
```
$ cd doctrine2/xml
$  sed -i 's/schema="vimbadmin"//g' *
```
This removes the schema from Doctrine, which gets it working again. The SQL changes can be inspected by adding --dump-sql at the end of the doctrine command like so:
```
./bin/doctrine2-cli.php orm:schema-tool:create --dump-sql
```

This is also the proper long term fix as far as I can see it, the Doctrine XML's should not be locked to a specific database. Althoug I am not sure if it's a Doctrine requirement, not a Doctrine superhero.

Make sure you drop any existing table before re-running the Doctrine DB setup commando, I find it easier to just drop and create the specified DB again from the MySQL / MariaDB console.

@barryo Maybe this can be added to the installation docs for the time being.

**Comment by laapsaap** [comment]
Seriously, in the 15 years that I have worked with PHP; this is the first time I seen a bug where you cannot change the database name. Is this what we get for adding so much more complexity in the frameworks ?  Anyways this bug is really annoying because you just dont expect it.

**Comment by barryo** [comment]
@laapsaap - nothing to do with the framework I imagine but rather a particular version of the tool we used to create the schema (Skipper). I haven't confirmed this but I suspect it is this.

**Comment by liayn** [comment]
@eXistenZNL Thanks a lot, this resolved #138.

```
$ cd doctrine2/xml
$ sed -i 's/schema="vimbadmin"//g' *
$ cd ../../
$ bin/doctrine2-cli.php orm:generate-entities application/
$ bin/doctrine2-cli.php orm:generate-proxies application/
$ bin/doctrine2-cli.php orm:generate-repositories application/
```

**Comment by eXistenZNL** [comment]
@liayn You're welcome :)

**Comment by idefix6** [comment]
Thanks for this, I added it to my fork that includes also some other modifications I require.
https://github.com/idefix6/ViMbAdmin

**Comment by klonos** [comment]
Sorry to resurrect this, but is this still an issue? Asking because this issue is linked from [the installation documentation -> DB setup](https://github.com/opensolutions/ViMbAdmin/wiki/Installation#database-setup).
