### ISSUE TITLE
Feature request: Add support for mail forwarding for mailboxes

### ISSUE THREAD

**Issue by vovochka404** [opensolutions/ViMbAdmin#125]
Cause each mailbox creates also records in aliases - there is no way to add alias like: user@example.com -> user@example.com,other@example.net

This is inconvenient.

It would be great to have possibility to add email for forwarding in mailboxes.

**Comment by barryo** [comment]
You'll be able to see these aliases by clicking the *Show mailbox aliases* icon on the top right of the aliases page:

![screenshot 2015-01-23 11 03 50](https://cloud.githubusercontent.com/assets/804649/5873553/9d1c89bc-a2ef-11e4-9fe3-80b2a99a4582.png)
