### ISSUE TITLE
Enabled purge and archive operations via ssh+sudo

### ISSUE THREAD

**Issue by peterschen** [opensolutions/ViMbAdmin#128]
For our production mailservers we try not to install anything besides the mail components on the mailserver. It would still be nice to have the ability to remove (purge) mailboxes and home directories when a user or domain is deleted.

It would be cool to have this feature implemented in a way which supports ssh (key based authentication) with sudo and local execution.

**Comment by barryo** [comment]
Should be fully possible to do this as is.
