### ISSUE TITLE
ViMbTool (cronjobs) cannot modify header

### ISSUE THREAD

**Issue by lucapretto** [opensolutions/ViMbAdmin#132]
I'm using ViMbAdmin 3.0.8 on Debian Wheezy. The system had been setup freshly from scratch.

It seems that ./bin/vimbtool.php can't work properly:

```
root@mail:~# /opt/vimbadmin/bin/vimbtool.php -a mailbox.get-sizes -d
Module:
Controller: mailbox
Action:     get-sizes

PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/vimbadmin/bin/vimbtool.php:108) in /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php on line 360

Warning: Cannot modify header information - headers already sent by (output started at /opt/vimbadmin/bin/vimbtool.php:108) in /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php on line 360
```

The same happens for
```
root@mail:~# /opt/vimbadmin/bin/vimbtool.php -a archive.archive-pendings -d
root@mail:~# /opt/vimbadmin/bin/vimbtool.php -a archive.delete-pendings -d
root@mail:~# /opt/vimbadmin/bin/vimbtool.php -a archive.restore-pendings -d
```

Could you give me a tip on how to solve it?

Thanks.

**Comment by liayn** [comment]
Would be interested as well

**Comment by barryo** [comment]
Where did you find this:

> /opt/vimbadmin/bin/vimbtool.php -a mailbox.get-sizes

As the correct version is:

> /opt/vimbadmin/bin/vimbtool.php -a mailbox.cli-get-sizes

All the CLI commands have a cli- prefix.

Please let me know where you found the incorrect version so I can update the documentation.

**Comment by liayn** [comment]
https://github.com/opensolutions/ViMbAdmin/blob/master/bin/crons/vimbadmin

**Comment by barryo** [comment]
Thanks, fixed.

**Comment by liayn** [comment]
Thanks.

Maybe you can also take care of the broken schema stuff, which prevents a successful upgrade (installation?) currently, when using a different DB name.
