### ISSUE TITLE
Archived accounts are stuck on "ARCHIVING"

### ISSUE THREAD

**Issue by florianbeer** [opensolutions/ViMbAdmin#133]
I have marked several mailboxes for archiving and the cronjob is set up to run.
Now the accounts are marked in the frontend as "ARCHIVING" and there are tar.bz2 files in the defined archive path, but they have only 46 bytes and the original maildirs are still in place.

The database shows the accounts in the "archive" table and not in the "mailbox" table anymore, but the status is "ARCHIVING" and all the homedir_* and maildir_* fields have "NULL" values. I also didn't ever get a mail for completed archives. Running the archive task on the CLI with "-v" doesn't show any errors.

Any help with figuring out what might have gone wrong or any more info I can provide to track down the error?

**Comment by barryo** [comment]
See: https://github.com/opensolutions/ViMbAdmin/wiki/Archiving-Mailboxes#cron-jobs

**Comment by florianbeer** [comment]
Of course I have the following lines in `/etc/cron.d/vimbadmin`

```
10 3 * * * someuser /var/www/vimbadmin/bin/vimbtool.php -a mailbox.cli-get-sizes > /dev/null                                                                      
10 */2 * * * someuser /var/www/vimbadmin/bin/vimbtool.php -a archive.cli-archive-pendings                                                                         
30 */2 * * * someuser /var/www/vimbadmin/bin/vimbtool.php -a archive.cli-restore-pendings                                                                         
50 */2 * * * someuser /var/www/vimbadmin/bin/vimbtool.php -a archive.cli-delete-pendings 
```

The issue must be somewhere in the archive task.

**Comment by barryo** [comment]
What happens when you run these manually on the command line with debug enabled?

    /var/www/vimbadmin/bin/vimbtool.php -d -a archive.cli-archive-pendings

**Comment by florianbeer** [comment]
```
Module:     
Controller: archive
Action:     cli-archive-pendings

No pending archives found.
```

**Comment by barryo** [comment]
So set a mail to be archived for testing and rerun please?
