### ISSUE TITLE
cant use another database name

### ISSUE THREAD

**Issue by radum706** [opensolutions/ViMbAdmin#139]
hello. i just installed vimbadmin on my server using other name for database (mysql) than vimbadmin, so i got an error installing database. it was creating only first table (domain_admins) and that was all. i used even the fix for that, but i did got same result. after renaming my db as vimbadmin and redo install db step, i managed to install it. tested and worked well. i tried renaming the database to something els, changing settings and i got back to same error:

File
    /var/www/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line
    53
Message
    An exception occurred while executing 'SELECT COUNT(a0_.id) AS sclr_0 FROM vimbadmin.admin a0_': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vimbadmin.admin' doesn't exist
Code
    0 
i tough it was a permission thing or something but after looking closely to that error i saw that it was searching for admin table in vimbadmin database. so, somewhere your script it's not using configured db name (from config file, ofc) but it go's back to vimbadmin.

P.S.: great project, thank you!

**Comment by idefix6** [comment]
If you like you can try my fork, there is this bug fixed and some additional features are added:
https://github.com/idefix6/ViMbAdmin

**Comment by barryo** [comment]
Just fixed with a new version tagged - 3.0.12.

Thanks!
