### ISSUE TITLE
Wiki Bug regarding .htaccess file

### ISSUE THREAD

**Issue by reissmann** [opensolutions/ViMbAdmin#141]
Hi,

there is a bug in your installation manual (https://github.com/opensolutions/ViMbAdmin/wiki/Installation), regarding the .htaccess file. This causes an 404 error as reported in #114 

The apache documentation for AllowOverride says:

    When this directive is set to None, then .htaccess files are completely ignored.
    In this case, the server will not even attempt to read .htaccess files in the filesystem.

You need to change the config example to this:
```apache
Alias /vimbadmin /usr/local/vimbadmin/public

<Directory /usr/local/vimbadmin/public>
    Options FollowSymLinks
    AllowOverride None

    # For Apache <= 2.3:
    Order allow,deny
    allow from all

    # For Apache >= 2.4
    # Require all granted

    SetEnv APPLICATION_ENV production

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^.*$ /vimbadmin/index.php [NC,L]
</Directory>
```
or allow the use of .htaccess, by not setting 
```apache
AllowOverride None
```

Regards and thanks for the software :)

**Comment by barryo** [comment]
Thanks and fixed!
