### ISSUE TITLE
Allow use of captcha on other locations

### ISSUE THREAD

**Issue by reissmann** [opensolutions/ViMbAdmin#142]
It would be really great to have the option to enable the captcha on the login page and on the "Mailbox password change" page!

I found the code that needs to be added to the templates, but I'm really not enough into Zend to implement verification myself ...

**Comment by barryo** [comment]
I agree this is a good idea but and I'm happy to review a PR on this but it's not an itch that we personally need scratched so can't assign resources to it :cry:
