### ISSUE TITLE
Add mailbox password scheme to database

### ISSUE THREAD

**Issue by PhrozenByte** [opensolutions/ViMbAdmin#146]
ViMbAdmin should store the used password scheme in the database, e.g. the password ```test``` hashed with ```crypt:sha512``` should be stored as
```
{SHA512-CRYPT}$6$UOfXG8URqAM2rLEe$26JgX1NyzTQA6SNfR3hSfx1BkoyxMSKQp6K9OkYeVdyX1ZSlMTiJzA3WAl1gdRYxosERICLOwjqH7/NXp09z51
```

This has some advantages:
* Dovecot can determine the used scheme on its own, no configuration necessary
* Admins can change the scheme without resetting all passwords
* Using ```doveadm``` has no advantages anymore :smiley:

I can implement this and make a pull request (just a few lines to change), but as far as I know you don't want updates of the database scheme in minor releases?

**Comment by kaechele** [comment]
There should be no database schema change required as it's just dovecot actually reading this field. Prepending the password scheme shouldn't break anything.

**Comment by PhrozenByte** [comment]
Just prepending the password scheme makes it impossible to differentiate between a built-in scheme and the use of `doveadm`. I didn't found a fully backward compatible solution without adding a new column.

**Comment by barryo** [comment]
I agree this is a good idea but it would probably require a major version bump. I'm happy to review a PR on this but it's an itch that we personally need scratched so can't assign resources to it :cry:
