### ISSUE TITLE
'Latest News' links lead to non-existing page

### ISSUE THREAD

**Issue by sdellenb** [opensolutions/ViMbAdmin#148]
##### Description
The links in the README.md and the footer templates for 'Latest News' and 'Keep up with ViMbAdmin' lead to a non-existing WordPress page on Barry O'Donovan's homepage.
* https://github.com/opensolutions/ViMbAdmin/blob/c24c04a97ffc1ece590c2f18e531fadec71d9cc6/README.md#L19
* https://github.com/opensolutions/ViMbAdmin/blob/c24c04a97ffc1ece590c2f18e531fadec71d9cc6/application/views/_skins/myskin/footer.phtml#L36
* https://github.com/opensolutions/ViMbAdmin/blob/c24c04a97ffc1ece590c2f18e531fadec71d9cc6/application/views/footer.phtml#L37

The actual link http://www.opensolutions.ie/blog/category/vimbadmin/ ends up at http://www.barryodonovan.com/category/vimbadmin/

##### Steps
1. On ViMbAdmin page, click the 'Keep up with ViMbAdmin' link on the bottom left.

##### Result
1. Shows some WordPress page with

> Not Found
> Apologies, but the page you requested could not be found. Perhaps searching will help.

##### Expected Result
Should probably go to somewhere on http://www.vimbadmin.net/ (note: the 'News' link on the official page also points to the same non-existing target).

_Personal note: I absolutely love ViMbAdmin. Thank you very much for your awesome work! :clap:
For some reason, this was only like the 4th or 5th solution I found googling, after postfixadmin, posty et al. which all were all nowhere as easy to setup and use as ViMbAdmin._

**Comment by barryo** [comment]
Thanks, all fixed.

I killed the Open Solutions blog last week as maintaining two was difficult at best! Appropriate redirects now in place.
