### ISSUE TITLE
(compressed) mdbox storage format support

### ISSUE THREAD

**Issue by virgo** [opensolutions/ViMbAdmin#149]
Hi,

I'd like to use vimbadmin with compressed mdbox storage format, but in many place are hardcoded maildir: and other wrong solutions (du, etc), so disk usage, archiving, deleting, etc don't works.
Can you improve app with compressed mdbox format?

Thanx
Laszlo

**Comment by barryo** [comment]
Hi @virgo - I'm happy to review a PR on this but it's an itch that we personally need scratched so can't assign resources to it :cry:
