### ISSUE TITLE
Unable to add Mailbox to a new TLD

### ISSUE THREAD

**Issue by SE0N** [opensolutions/ViMbAdmin#151]
Hi maybe this can be resolved on another way but I have the issue, that I can on the one hand add a new tld like xyz.online, but I can't add a mailbox to it (like: admin@xyz.online).

It just says: Invalid email address. 

Can someone give me a hint on how to avoid the mail check or in which file it is, so that I can disable it?

**Comment by SE0N** [comment]
Ok seems to be a problem with the Zend_Validate.

I removed the Zend_Validate in Line 275 of the MailboxController.php and now I can add them.

But if you need to validate the complete email for your mail adresses, you shouldn't comment it out.

**Comment by extremeshok** [comment]
You should just validate the email address contains :
No invalid characters
Has text @ and a .

Unless you want to issue daily updates for each new tld being released.

**Comment by SE0N** [comment]
The problem was with the Zend_Validate in the tool. I had no invalid characters or something like that in neither the domain nor the name (it was just admin as name and my domain with .online as the domain) For every other domain with .com or .de or .eu I could add a box with the same name, just for .online it wasn't possible. So my guess was, that Zend_Validate makes some more validations in the background with the tlds.

**Comment by s256** [comment]
Commented the "if" case in line #65 out  in  ViMbAdmin/application/views/alias/js/add.js
` if( address.substr( 0, 1 ) == '@' && isValidEmailDomain( address.substr( 1 ) ) || isValidEmail( address ) )`  
It's working now.
