### ISSUE TITLE
Error creating mailbox for long TLDs

### ISSUE THREAD

**Issue by ricobeck** [opensolutions/ViMbAdmin#153]
I have an .agency-domain and was able to add it in the domain section. But every time i try to create a new mailbox I get the following error:
> An unexpected error has occured.

I can't find any hints in the logs. What could be the problem?

**Comment by barryo** [comment]
Check `$INSTALL_DIR/var/logs/...` and you should find a stack trace.

**Comment by ricobeck** [comment]
I'm sorry but there is absolutely no hint. The logfile contains only the info message about my login. No error and no stack trace. I'm a bit lost ...

**Comment by barryo** [comment]
I have no issues adding .agency domains and mailboxes using ViMbAdmin checked out from master.

Are you using a release version? If so, can you pull from master instead?

Can you also enable debugging in `application/config/application.ini` by changing the following as shown:

    phpSettings.display_startup_errors = 1
    phpSettings.display_errors = 1
    resources.frontController.params.displayExceptions = 1

**Comment by barryo** [comment]
Should be fixed.
