### ISSUE TITLE
Option to forward to a script? Email piping with Vimbadmin

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [opensolutions/ViMbAdmin#155]
Hi there!

Is there a possibility to setup email piping with vimbadmin? 
When I try adding a file path to a php script to the alias forwarding field it returns an error saying that this is not a valid email address.

When I enter a pipe sign in the beginning of the filepath I also get an error.

Would be nice if that was possible somehow. 

Use case: ticket system/support system/ help desk software

**Comment by kaechele** [comment]
I guess this is pretty much out of scope for ViMbAdmin. Combining virtual and local delivery (which is required for piping) agents in Postfix to pipe email into scripts requires configuration changes on the postfix side (in master.cf) for every piped alias you want to create.
I don't really (want to) see ViMbAdmin fiddling with postfix config files.

Also see here: http://serverfault.com/questions/258469/how-to-configure-postfix-to-pipe-all-incoming-email-to-a-script
