### ISSUE TITLE
Autoconfig of mail clients?

### ISSUE THREAD

**Issue by pierreozoux** [opensolutions/ViMbAdmin#157]
Would you be interested in adding autoconfiguration of mail to this project?

I already did it in this project: https://github.com/indiehosters/email/blob/master/vimbadmin/Dockerfile#L51-L52 so I could pull request?

**Comment by extremeshok** [comment]
Interesting.

What dns records does one need to set for the autoconfig ?

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by pierreozoux** [comment]
Pour apple rien de spécial.
Pour thunderbird l'un ou l'autre:
  - http://autoconfig.example.com/mail/config-v1.xml
  - http://example.com/.well-known/autoconfig/mail/config-v1.1.xml

**Comment by kaechele** [comment]
I use automx[1] together with ViMbAdmin. They go along very well because automx can use the SQL Database as a backend.
This tool can autoconfigure several clients such as Outlook, Thunderbird and iOS/OS X devices (even with code signed configuration profiles!).

[1]: https://automx.org/en/

**Comment by pierreozoux** [comment]
@kaechele I tried to set it up, but had troubles to configure it in docker :/ 

Maybe I should give another try!

**Comment by barryo** [comment]
Link in OP no longer works. Closing.

**Comment by pierreozoux** [comment]
@barryo I don't understand your comment, could you develop?

**Comment by barryo** [comment]
Hi @pierreozoux - I mean the link you posted doesn't work:

https://github.com/indiehosters/email/blob/master/vimbadmin/Dockerfile#L51-L52

Do you have an updated link?

**Comment by pierreozoux** [comment]
Sorry, got it.

Here are the files I'm using:
https://github.com/indiehosters/docker-vimbadmin/blob/master/mail.mobileconfig.php
https://github.com/indiehosters/docker-vimbadmin/blob/master/mozilla-autoconfig.xml
https://github.com/indiehosters/docker-vimbadmin/blob/master/patch

But well, let me know if you are interested, then I can PR.
