### ISSUE TITLE
config defaults.mailbox.min_password_length not working

### ISSUE THREAD

**Issue by netdesk** [opensolutions/ViMbAdmin#158]
I tried to change the configuration "defaults.mailbox.min_password_length" in application/configs/application.ini. It has no effect. Doesn't matter if you change it to less or more than 8, it always validates to 8 characters (server side validation) when creating new mailboxes or changing the password of existing mailboxes.

**Comment by Acetylator** [comment]
Confirmed in version 3.0.12 (Debian Jessie). defaults.mailbox.min_password_length does NOT work.

**Comment by netdesk** [comment]
Forgot to mention my configuration: Version 3.0.12 on Debian Jessie too.
