### ISSUE TITLE
Zend_Controller_Action_Exception on fresh installation

### ISSUE THREAD

**Issue by dmitrydonskih** [opensolutions/ViMbAdmin#159]
Hello, I've faced such error on a fresh installation of ViMbAdmin:
> Fatal error: Uncaught exception 'Zend_Controller_Action_Exception' with message 'ViewRenderer initialization failed: retrieved view base path is empty' in /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php:475 Stack trace: #0 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(516): Zend_Controller_Action_Helper_ViewRenderer->initView() #1 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(253): Zend_Controller_Action_Helper_ViewRenderer->init() #2 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(132): Zend_Controller_Action_HelperBroker->__construct(Object(ErrorController)) #3 /opt/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Controller/Action.php(119): Zend_Controller_Action->__construct(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http), Array) #4 /opt/vimbadmin/library/ViMbAdmin/Controller/Actio in /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php on line 336

CentOS 6.6, fresh git-2.6.3, composer -1.0-dev, php-5.4.45, nginx.
I've downloaded tarball `vimbadmin-3.0.12`, installed with composer (all ok), setup database (schema validation ok), set file permissions on `var/`, copy-edit `application.ini` from *.dist, copy `.htaccess` from *.dist, test it with `php -S lo:8080 -t public/` and get an error... What have I missed?

**Comment by LNQ** [comment]
+1

**Comment by lexpierce** [comment]
+1

**Comment by hassansin** [comment]
Same for me.

**Comment by barryo** [comment]
Folks - I have done an install from scratch following [the official instrauctions](https://github.com/opensolutions/ViMbAdmin/wiki/Installation) and I cannot recreate the above.

I note that PHP5.4 is mentioned above which is end of life.

Is anyone using a newer version? My test was on 7.0.

**Comment by justnick** [comment]
It's not because of the php version, I've installed php 5.6 after seeing this with the default 5.4.16 on CentOS 7 and the error was still there. 

After taking a closer look I saw the following error:
```[Fri Jan 22 13:10:17 2016] PHP Fatal error:  Uncaught exception 'Zend_Filter_Exception' with message 'The given encoding 'ISO-8859-1' is not supported by mbstring' in /var/www/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Filter/StringToLower.php:97```
After installing the `php-mbstring` rpm the error went away.

I've tried a few things simultaneously at the time, therefore I can't be sure that was what solved it, but you can give it a try.

**Comment by barryo** [comment]
I tend to always have mbstring installed. @hassansin  / @lexpierce / @LNQ / @dmitrydonskih - can any of you confirm if installing mbstring (and restarting apache / the PHP web server helps)?

**Comment by dmitrydonskih** [comment]
Looks like YES, it worked for me.
+php54w-mbstring
+php54w-pear
+php54w-pecl-memcache
+php54w-pecl-memcached
did the job.

**Comment by barryo** [comment]
Great - added a note in the documentation. Thanks!

**Comment by hassansin** [comment]
Yup, enabling `mbstring` did the trick!

**Comment by lexpierce** [comment]
Fixed here. Thanks!

**Comment by hassansin** [comment]
And if running with docker official php image, you need both 'mbstring' and 'gettext' extensions:

    RUN docker-php-ext-install  mbstring  gettext
