### ISSUE TITLE
Please add online mail.log viewer

### ISSUE THREAD

**Issue by AlexGnatko** [opensolutions/ViMbAdmin#160]
Hi!

Thank you for the great job you've done making ViMbAdmin!

I'm migrating to a postfix/dovecot/ViMbAdmin e-mail solution from a CommuniGate Pro e-mail server.

There is one feature I'm going to miss that CommuniGate Pro has and ViMbAdmin doesn't - that's the mail log file viewer. Sometimes a client reports some problem with e-mail, and taking a look at the log file is usually the first thing to do. Of course, I could view the file in mc over a SSH terminal, for example. But that's not as easy as just logging in to ViMbAdmin, opening a log file viewer, entering the client's e-mail to filter the output, and browsing the log right there. CommuniGate Pro is very convenient in that sense.

I think this kind of feature would be very simple to make, but could add a lot of value to ViMbAdmin.

**Comment by barryo** [comment]
Sorry - this is out of scope for ViMbAdmin. ViMbAdmin is mainly a database front end and doesn't interact with mail daemons directly.
