### ISSUE TITLE
Fatal error: Class 'Doctrine\Common\Cache\ArrayCache' not found in 

### ISSUE THREAD

**Issue by maxg10** [opensolutions/ViMbAdmin#162]
Hello,

After an upgrade to the latest version trying to access vimbadmin i see the following error in the browser:
Fatal error: Class 'Doctrine\Common\Cache\ArrayCache' not found in /var/www/html/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Doctrine2cache.php on line 124

Ubuntu 14.04.3 LTS
Any help appreciated.
regards,
M.

**Comment by maxg10** [comment]
OK, just reinstalled again and it works OK.

**Comment by boscorelly** [comment]
i have the same issue with a freshly downloaded zip for the latest version

**Comment by boscorelly** [comment]
complete new install with git solved it.
strange...
