### ISSUE TITLE
New TLD Support (Alias)

### ISSUE THREAD

**Issue by s256** [opensolutions/ViMbAdmin#164]
It's not possible to add multiple recipients (Goto) to an Alias if it's a new TLD. In my case .business .
Domain was added successfully. One Alias is also not a problem. Just multiple recipients.

**Comment by s256** [comment]
I'm correcting: If the TLD part is longer than 4 Characters. I assume AliasController.php is the responsible file. First I thought it's the Zend Framework. But after removing `!Zend_Validate::is( "{$address}", 'EmailAddress', array( 1, null ) )` nothing changed.
I'm not sure if it's the correct file, but it was the only one I could finde the exact error message.
I'm not a programmer, just an admin. Sorry :/
Line 428 in AliasController.php 
`        // is the alias valid (allowing for wildcard domains (i.e. with no local part)
        if( $form->getValue( "local_part" ) &&  !Zend_Validate::is( "{$address}", 'EmailAddress', array( 1, null ) ) )
        {
            $form->getElement( 'local_part' )->addError( _( '**Invalid email address**.' ) );
            return false;
        }`

**Comment by SE0N** [comment]
Maybe this helps: https://github.com/opensolutions/ViMbAdmin/issues/151

At least this was what helped me for the new TLDs

**Comment by barryo** [comment]
Seems to work fine now. I'll create a new release shortly.
