### ISSUE TITLE
IDN domain support

### ISSUE THREAD

**Issue by vadimkim** [opensolutions/ViMbAdmin#165]
I can save IDN  domain to Domains, but when I create alias - any name, except blank gives error "invalid e-mail"

**Comment by SE0N** [comment]
What TLD are you trying to use? If it is a newer TLD it may be filtered by the Zend Form Validation as a not valid TLD. (I had that issue with a .online Domain)

https://github.com/opensolutions/ViMbAdmin/issues/151

**Comment by vadimkim** [comment]
the issue is with this domain name: xn--80afvemcl9d.xn--p1ai
This is a national domain. Should  work correctly.

**Comment by vadimkim** [comment]
I have tried to add e-mails like info@, postmaster@ and so on...

**Comment by mhaze4** [comment]
I have the same issue.

I can add an IDN to domains but cannot assign a mailbox to the domain.
Same error: 'invalid email address'.
