### ISSUE TITLE
Help desperately needed

### ISSUE THREAD

**Issue by ffxsam** [opensolutions/ViMbAdmin#166]
Could someone give an example of how to put vimbadmin in a subfolder, in nginx? For the life of me, I cannot figure this out.

e.g. vimbadmin lives in `/var/www/vimbadmin`, and I want to access it by going to mydomain.com/vimbadmin.

**Comment by barryo** [comment]
This may help: https://github.com/opensolutions/ViMbAdmin/wiki/Installation#nginx

If not, please ask on a Nginx forum as it's not ViMbAdmin specific. In general, any instructions for installing a PHP app under a subdirectory should work.
