### ISSUE TITLE
lost password - error

### ISSUE THREAD

**Issue by Jaispirit** [opensolutions/ViMbAdmin#173]
Hi there
While clicking on 'Lost Password' an error appears. Any idea how to fix that?
_Uh oh! Unexpected Error!_
Thank you in advance.

**Comment by barryo** [comment]
You'll need to provide logs showing the exception. 

Most likely you're missing the php-gd extension to create the Captcha image.

Closing for now - reopen if this does not solve / if you can share the exception trace from logs.

**Comment by pierreozoux** [comment]
I'm seeing the same error here:
https://mail.indie.host/auth/lost-password

Actually I think everthing is installed:
https://github.com/indiehosters/docker-vimbadmin/blob/master/Dockerfile

I followed these install steps:
https://github.com/opensolutions/ViMbAdmin/wiki/Installation

I don't see any logs from my server :/

Could you help me, or tell me how I can help you?

thanks!

**Comment by barryo** [comment]
Hi @pierreozoux - I'm afraid there's very little I can do without logs.

Can you change `application/configs/application.ini` to display running and startup errors?

**Comment by pierreozoux** [comment]
Ok, I found the log actually :)

```
Message: Image CAPTCHA requires FT fonts support
```

I fixed it by adding freetype support to gd.
Here is the commit that fixed it:
https://github.com/indiehosters/docker-vimbadmin/commit/ef1c15fc5b6e92f6a3c79bc9ee01ba5fe51a869d

**Comment by barryo** [comment]
Great, thanks for the update.
