### ISSUE TITLE
Remove composer's autoload section for Smarty

### ISSUE THREAD

**Issue by PhrozenByte** [opensolutions/ViMbAdmin#176]
ViMbAdmin's `composer.json` currently contains a autoloader section for Smarty:
```json
    "autoload": {
        "classmap": [
            "vendor/smarty/smarty/libs/Smarty.class.php",
            "vendor/smarty/smarty/libs/SmartyBC.class.php",
            "vendor/smarty/smarty/libs/sysplugins/smarty_security.php"
        ]
    }
```

However, this isn't necessary anymore because Smarty now (I've no idea since when) registers its autoloader itself, see https://github.com/smarty-php/smarty/blob/v3.1.29/composer.json#L30-L36

I think this is a leftover from d91b97f (see #168/#169). You can safely remove the whole `autoload` section.

**Comment by barryo** [comment]
Thanks @PhrozenByte :+1:
