### ISSUE TITLE
3.0.12 shown on frontpage after upgrade, instead of 3.0.13

### ISSUE THREAD

**Issue by Whichcraft** [opensolutions/ViMbAdmin#177]
3.0.12 shown on frontpage after upgrade, instead of 3.0.13 which is stated in:

$grep VERSION * -r
library/ViMbAdmin/Version.php:    const VERSION = '3.0.13';

**Comment by barryo** [comment]
Ummm.... it's not:

![screen shot 2016-04-04 at 09 34 24](https://cloud.githubusercontent.com/assets/804649/14242349/7a328cc4-fa48-11e5-9cd2-e65eaed2d5e4.png)

Try a forced refresh / cache clear / etc.

**Comment by Whichcraft** [comment]
aehm it is for me. i've cleaned the caches, used other browser. I followed UPGRADING, unzipped it over old instance.

pwd
/srv/vimbadmin/public

grep VERSION * -r
application/views/footer.phtml:                <a href="https://github.com/opensolutions/ViMbAdmin/releases">V{ViMbAdmin_Version::VERSION}</a>.
application/views/_skins/myskin/footer.phtml:            <a href="https://github.com/opensolutions/ViMbAdmin/wiki">ViMbAdmin V{ViMbAdmin_Version::VERSION}</a>.
application/controllers/AuthController.php:                    $dbversion->setVersion( ViMbAdmin_Version::DBVERSION );
application/controllers/AuthController.php:                    $dbversion->setName( ViMbAdmin_Version::DBVERSION_NAME );
bin/doctrine2-cli.php:$cli = new \Symfony\Component\Console\Application( 'Doctrine Command Line Interface', Doctrine\Common\Version::VERSION );
library/ViMbAdmin/Version.php:    const VERSION = '3.0.13';
library/ViMbAdmin/Version.php:    const DBVERSION = 1;
library/ViMbAdmin/Version.php:    const DBVERSION_NAME = 'Venus';

![vimbadmin](https://cloud.githubusercontent.com/assets/6341584/14243772/b171c8d0-fa57-11e5-87e5-87f1cfb983b0.png)

**Comment by barryo** [comment]
Try rm'ing all files from VIMBADMIN_ROOT/var/templates_c

**Comment by Whichcraft** [comment]
ls -alih templates_c/
total 12K
158992 drwxr-xr-x 2 root root 4.0K Apr  2 14:07 .
 14702 drwxr-xr-x 7 root root 4.0K Apr  2 14:07 ..
158994 -rw-r--r-- 1 root root   10 Apr  2 14:07 .hello-git
[root@mail var]# rm templates_c/.hello-git 
rm: remove regular file ‘templates_c/.hello-git’? y

didn't change anything. Of course I've deleted all caches one more time. Well, I know, it's a minor problem.

**Comment by barryo** [comment]
Shrug... works on my production and dev installs so not sure what's different about yours :cry:
