### ISSUE TITLE
Non Super-admin can change domain quota

### ISSUE THREAD

**Issue by fabiorauber** [opensolutions/ViMbAdmin#181]
A non super-admin user can change the max quota for the domain for which he is admin. I believe this is a bug, because the Wiki on Quotas describes max quota as:

_NB: maxquota does not define a maximum allowed quota over the entire domain. It just sets an upper limit that non-super admins can set per mailbox._

Well, if the super admin sets the quota on example.com to be 500MB, a non super-admin of example.com can change the quota to 1GB first and the proceed to create 1GB mailboxes.

**Comment by PhrozenByte** [comment]
IMHO domain admins (non super admins) shouldn't be able to edit domains whatsoever. They should be able to manage mailboxes and aliases and activate/deactivate the domain, but nothing else.

**Comment by click** [comment]
This is the same as reported in ticket #30, which was closed - @barryo, in the case of non-admins viewing the domain details for quota, might it be easier to just print the value, and not using a editbox?
