### ISSUE TITLE
Possibility to set one or more alias for a domain

### ISSUE THREAD

**Issue by Sebi94nbg** [opensolutions/ViMbAdmin#182]
I can't find a way to set an alias for my domains.

I want to say, that *@domain.de is forwarded to *@domain.com for example.

Does this feature already exists? If not, please add it and if yes, how and where can I use this?

Thank you for your awesome work! :+1:

**Comment by PhrozenByte** [comment]
See the `?` buttons next to the input fields when creating a new alias. Simply leave the local part of the alias empty and specify just `@[domain]` as goto address (Address: `@domain.de`; Goto: `@domain.com`).

**Comment by Sebi94nbg** [comment]
Ah, awesome!

Thank you! :+1:
