### ISSUE TITLE
dovecot: lmtp Error sieve: sieve script file path ~/.dovecot.sieve is relative to home directory, but home directory is not available.

### ISSUE THREAD

**Issue by Sebi94nbg** [opensolutions/ViMbAdmin#183]
I'm getting following error messages in _/var/log/mail.log_:
```
dovecot: lmtp(28787, user@example.com): Error: User user@example.com doesn't have home dir set, disabling duplicate database
dovecot: lmtp(28787, user@example.com): Error: v0THAoYlEVdzcAAARcn2aQ: sieve: sieve script file path ~/.dovecot.sieve is relative to home directory, but home directory is not available.
dovecot: lmtp(28787, user@example.com): Error: v0THAoYlEVdzcAAARcn2aQ: sieve: failed to access user's Sieve script ~/.dovecot.sieve (temporary failure)
```
Did I miss something?

**Comment by PhrozenByte** [comment]
`User user@example.com doesn't have home dir set`

See https://github.com/opensolutions/ViMbAdmin/wiki/Configuration#mailbox-settings-and-defaults

**Comment by Sebi94nbg** [comment]
Do I need to create all sub-directories manually after creating a new account/alias?

Die entire path _/srv/vmail/%d/%u/_ (/srv/vmail/example.com/user/) does exists for this user, but the mail directory inside of it not for example. Otherwise, the mail/ directory was created for two of four new email accounts...

I'm using the default configuration except the _password_scheme_.

I'll delete all domains, email accounts and aliases and re-create them all. I'll update this issue later.

**Comment by Sebi94nbg** [comment]
@PhrozenByte I'm confused. Why does it not work? I'm always just getting "OK, Mailbox was created successful" and the above mentioned log messages...

I've configured following (default):
```
defaults.mailbox.maildir = "maildir:/srv/vmail/%d/%u/mail:LAYOUT=fs"
defaults.mailbox.homedir = "/srv/vmail/%d/%u"
```
```
# ls -lha /srv/vmail/
insgesamt 32K
drwxr-xr-x 4 vmail vmail 4,0K Apr 16 16:11 .
drwxr-xr-x 3 root  root  4,0K Apr 16 13:19 ..
-rw------- 1 vmail vmail  314 Apr 16 16:08 .bash_history
-rw-r--r-- 1 vmail vmail  220 Apr  9  2014 .bash_logout
-rw-r--r-- 1 vmail vmail 3,6K Apr  9  2014 .bashrc
drwx------ 3 vmail vmail 4,0K Apr 16 16:11 example.com
-rw-r--r-- 1 vmail vmail  675 Apr  9  2014 .profile
```
```
# ls -lha /srv/vmail/example.com/user/
insgesamt 8,0K
drwx------ 2 vmail vmail 4,0K Apr 16 16:10 .
drwx------ 4 vmail vmail 4,0K Apr 16 16:10 ..
```
Is the webinterface may not able to create the mail/ directory due the permissions are only 0700 instead of 0755? Can I change this behaviour anywhere?

**Comment by PhrozenByte** [comment]
You missed the important part of the linked wiki article:
> Needs to match your Dovecot configuration.

ViMbAdmin doesn't create any of these files. This isn't a misconfiguration of ViMbAdmin, it's a misconfiguration of Dovecot (as `/var/log/mail.log` tells you). Maybe the SQL query you configured for Dovecot is wrong. Unfortunately I can't help you with that, sorry. Dovecot doesn't seem to recognize the homedir correctly.

**Comment by Sebi94nbg** [comment]
Oh, yes. That was it. Thank you very much! :+1: 

I've corrected following lines in _/etc/dovecot/conf.d/10-mail.conf_:
```
mail_home = /srv/vmail/%d/%u
mail_location = maildir:/srv/vmail/%d/%u/mail:LAYOUT=fs
```

Dovecot and ViMbAdmin has now the same mail_home and mail_location set.
