### ISSUE TITLE
[Security Suggestion] Password field and initial password

### ISSUE THREAD

**Issue by Sebi94nbg** [opensolutions/ViMbAdmin#184]
Currently, you can set a password and it will be displayed in clear-text instead of censored. Please change the input field to password instead of text and add a second one to validate the entered password.

If needed, you may can add a "View password" button, which temporarly changes the password-field to a text-field.

If the user uses the "create a random password" button, it should be automatically set to both input fields.

Anyway: In my opinion it's a no go, to send out the set password in clear-text via email to the user.

I would prefer, that the password isn't sent out, if at creation of the mailbox an individual password was set. If it's a random password, it should be send seperatly in a second email and/or the user has to change it immediately after the first login. This action needs to be forced at login.

**Comment by Sebi94nbg** [comment]
Any news regarding this topic?

**Comment by barryo** [comment]
Haven't had a chance to look at this. A PR would be welcome to move things along.

**Comment by Sebi94nbg** [comment]
Sorry, didn't get that. What would be welcome?

**Comment by barryo** [comment]
PR => Pull Request (i.e. code)

**Comment by Sebi94nbg** [comment]
Ah, ok. Yes, when I can find some time at weekend, I'll try to figure out a solution.

**Comment by Sebi94nbg** [comment]
@barryo has this been changed?

**Comment by barryo** [comment]
No @Sebi94nbg - just closing it for 'timeout' - dates from 2016 😉

**Comment by barryo** [comment]
(still happy to look at a PR of course)
