### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Zend_Controller_Response_Exception'...

### ISSUE THREAD

**Issue by EmJotGeh** [opensolutions/ViMbAdmin#185]
Hi@all

it`s the second try to install ViMbAdmin 3.0.15 on Debian Jessie with the php-composer
Apache/2.4.10
PHP Version 5.6.19-0+deb8u1

But i get this error message and i have no idea why?

`PHP Fatal error:  Uncaught exception 'Zend_Controller_Response_Exception' with message 'Cannot send headers; headers already sent in , line 0' in /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php:323\nStack trace:\n#0 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php(341): Zend_Controller_Response_Abstract->canSendHeaders(true)\n#1 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php(768): Zend_Controller_Response_Abstract->sendHeaders()\n#2 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(992): Zend_Controller_Response_Abstract->sendResponse()\n#3 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()\n#4 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()\n#5 /srv/vimbadmin/public/index.php(34): Zend_ in /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php on line 323, referer: https://my.Domain/admin/public/index.php/auth/login`

Webroot permissions should be fine:

3149959 4 drwxr-xr-x 3 root     root     4096 Apr 18 01:38 .
3148972 4 drwxr-xr-x 4 root     root     4096 Apr 18 01:38 ..
3149960 4 drwxr-xr-x 3 www-data www-data 4096 Apr 18 03:17 htdocs

1573139  4 drwxr-xr-x  6 www-data www-data  4096 Apr 18 01:53 .
2359298  4 drwxr-xr-x 10 root     root      4096 Apr 18 01:35 ..
1573142  4 drwxr-xr-x  3 www-data www-data  4096 Apr 18 01:34 css
1573206  4 -rw-r--r--  1 www-data www-data   894 Apr 18 01:34 favicon.ico
1576710  4 -rw-r--r--  1 root     root       241 Apr 18 01:53 .htaccess
1573140  4 -rw-r--r--  1 www-data www-data   241 Apr 18 01:34 .htaccess.dist
1573207  4 drwxr-xr-x  6 www-data www-data  4096 Apr 18 01:34 images
1573265  4 drwxr-xr-x  2 www-data www-data  4096 Apr 18 01:34 img
1573268  4 -rw-r--r--  1 www-data www-data  1038 Apr 18 01:34 index.php
1573269  4 drwxr-xr-x  2 www-data www-data  4096 Apr 18 01:34 js
1573141 56 -rw-r--r--  1 www-data www-data 56744 Apr 18 01:34 PiwikTracker.php

 

i can log in but nothing more... 

![vimbadmin_2016-04-18_03-55-29](https://cloud.githubusercontent.com/assets/16000642/14591940/b37b758c-0519-11e6-9e85-433dc2b48aa5.jpg)

thanks for help

**Comment by barryo** [comment]
Hi @EmJotGeh - install issues should be taken up on the mailing list rather than GitHub Issues.

You might find some hints in either the Apache log file or in `VIMBADMIN_INSTALLDIR/var/logs`.
