### ISSUE TITLE
Erro ao executar o projeto

### ISSUE THREAD

**Issue by kailtom-monteiro** [opensolutions/ViMbAdmin#188]
`2016/04/23 15:09:42 [error] 28575#0: *1422895 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/22222/htdocs/vimbadmin/application/../v$$n/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/22222/htdocs/vimbadmin/public/index.php on line 12
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/22222/htdocs/vimbadmin/application/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear:') in /var/www/22222/htdocs/vimbadmin/public/index.php on line 12" while reading response header from upstream, client: 189.90.32.142, server: , request: "GET /vimbadmin/public/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "meusite.com.br:22222"

`

**Comment by kailtom-monteiro** [comment]
Após instalar o ViMbAdmin executo o link: meusite.com.br:22222/vimbadmin e em seguida o erro é lançado.

**Comment by PhrozenByte** [comment]
Sorry, you must speak English to get help. The good news is that the error message (`PHP Fatal error: require_once(): Failed opening required '/var/www/22222/htdocs/vimbadmin/application/../vendor/autoload.php'`) already tells us what the problem is. Please refer to https://github.com/opensolutions/ViMbAdmin/wiki/Installation for installation instructions. You'll need to run `composer install`.

**Comment by kailtom-monteiro** [comment]
According to rtcamp the problem is generated by:

Issue is with composer json file in Vimbadmin.

Requested a pull request fixing the issue. This issue will be solved as soon as maintainer of Vimbadmin get on this Pull Request.

**Comment by barryo** [comment]
What's the issue with composer.json?

**Comment by kailtom-monteiro** [comment]
Boa noite! O problema já foi resolvido! Não tinha nada haver com o composer.json. Assim sendo o problema era na configuração do ViMbAdmin, não estava correto!
