### ISSUE TITLE
ViMbAdmin and PHP 7

### ISSUE THREAD

**Issue by luckyjay** [opensolutions/ViMbAdmin#192]
Hi, I recently updated a system to Ubuntu 16, which brought along PHP 7. This caused some heartburn with ViMbAdmin. I am running 3.0.10, unsure if a newer version would help though.

There were two things I had to change to make it work:

1) Disable Memcached and went back to ArrayCache in vimbadmin/application/configs/application.ini
2) Edited vimbadmin/vendor/doctrine/common/lib/Doctrine/Common/ClassLoader.php and made changes at line 248 per the suggestion found here http://serverfault.com/questions/743386/zend-framework-on-php-7

**Comment by barryo** [comment]
Hi,

to test this I finally rolled a Vagrant environment for ViMbAdmin:

https://github.com/opensolutions/ViMbAdmin/wiki/Vagrant

> 1) Disable Memcached and went back to ArrayCache in vimbadmin/application/configs/application.ini

Works with: ``apt install php-memcache``

> 2) Edited vimbadmin/vendor/doctrine/common/lib/Doctrine/Common/ClassLoader.php and made changes at line 248 per the suggestion found here http://serverfault.com/questions/743386/zend-framework-on-php-7

Also works with latest Doctrine updates (run ``composer update``).

Thanks,
Barry
