### ISSUE TITLE
[Enhancement] custom attributes to Domains/Mailboxes/Aliases

### ISSUE THREAD

**Issue by dmitrydonskih** [opensolutions/ViMbAdmin#194]
Hello all.
What about giving administrator the ability to extend database schema, add user fields to Domains/Mailboxes/Aliases tables and make them editable? This could be used, in example, to store user preferences related to antivirus/antispam sofware, security settings, grouping objects by some attribute, etc.
As a good example, you may have a look at one lightweight CMS here: [http://rukovoditel.net/demo.php](http://rukovoditel.net/demo.php). Login as admin/admin, then go to Application structure - Users - Field configuration - Add new field.
I think this would be a great encancement.

**Comment by maysara** [comment]
+1
I would want this to be possible to enter; even if it was a json blob where i could add a phone number, name or simply a comment. this sound a bit like a mini directory.

@dmitrydonskih , maybe having this as a separate table/database through some sort of plugin; either to have additional fields to fill (on creation) or an external id to link to an external system(where then additional info can be fetched and displayed for an admin); yet mostly to enter/modify data ...

any pointers if hooks or some plug/extension framework that can be used or other ideas to achieve this without bloating the code?

**Comment by maysara** [comment]
I've noticed Entities.DirectoryEntry.dcm.xml in doctrine2, somehow it seems very promising but I cannot find any reference to it and/or how its used in vimbadmin ... any hints would be appreciated!

**Comment by barryo** [comment]
This is quite a big FR and not within our current plans or time. Contact me if this is something you want to fund commercially.

This could also be handled via plugins.
