### ISSUE TITLE
add general aliases for new domain

### ISSUE THREAD

**Issue by nysander** [opensolutions/ViMbAdmin#196]
is it possible to make hook for new domain or check existing one if it has email addreses (mailboxes or aliases) that conform RFC 2142, and if there are no such adds them.

best option will be to be able to choose if they will be mailboxes / aliases (choice fields) and if aliases where to deliver

**Comment by idefix6** [comment]
Please check #179, is that what you are locking for?

**Comment by nysander** [comment]
yep that is, I will continue discussion there
