### ISSUE TITLE
[Feature Request] Public/Private alias (mailing list)

### ISSUE THREAD

**Issue by Sebi94nbg** [opensolutions/ViMbAdmin#202]
By adding a simple boolean option called "Public/Private", you could create an "Alias", where...
- Public: ...everybody would be able to send emails to this "mailing list".
- Private: ...only the listed emails in the Alias would be able to send emails to this "mailing list".

This is useful for external and internal usage. For example should only the team be able to send emails to team@company.com. This would be possible, if you can set this alias to "Private".

**Comment by barryo** [comment]
I don't think this feature is appropriate to ViMbAdmin.

What you're describing is best accomplished via something like [Mailman](https://www.gnu.org/software/mailman/) or [Majordomo](http://www.greatcircle.com/majordomo/). See also [some alternatives listed here](http://serverfault.com/questions/72940/alternatives-to-mailman).
