### ISSUE TITLE
Has anyone setup fail2ban filter for vimbadmin?

### ISSUE THREAD

**Issue by wcat13** [opensolutions/ViMbAdmin#206]
looking at opening up vimbadmin for customer password reset and wondering how to best protect it from abuse.

**Comment by barryo** [comment]
You can set up fail2ban filters for the Apache log - e.g. on:

10.5.6.8 - - [21/Sep/2016:23:42:03 +0100] "POST 
/vimbadmin/auth/lost-password HTTP/1.1" 302

Note that ViMbAdmin will send you to the password reset page whether you 
entered a right email or not - note the message:

"If your username was correct, then an email with a key to allow you to 
change your password below has been sent to you."

  - Barry



WCat wrote:

**Comment by wcat13** [comment]
OK, thank you Barry.  Great product that has served me well for a few years now.
