### ISSUE TITLE
[Feature request] (REST) API for ViMbAdmin

### ISSUE THREAD

**Issue by marceldeglau** [opensolutions/ViMbAdmin#207]
Hey developers!

I have a simple feature request for ViMbAdmin: **(REST) API over HTTP.**

Why: I am currently using ViMbAdmin for my mailserver(s) management. In the future I want to add some customers to this mailserver(s). I want to build an panel for my customers where they can manage his mailboxes. 
I think also there are some other examples for a REST API. If anyone have time to build a simple API it will fantastic. 

I'm looking forward to hear from yours!

**Comment by barryo** [comment]
Bad news: #193
