### ISSUE TITLE
Promote mailbox to admin

### ISSUE THREAD

**Issue by pierreozoux** [opensolutions/ViMbAdmin#208]
Would it be possible to promote a mailbox user to administrator?

This way people would have one login for their mailbox and to administer their domain for instance.

**Comment by barryo** [comment]
These are separate tables in the current schema. The thinking being not every mailbox will be an administrator and not every administrator will be a mailbox user. It also allows better password hashing in the admin table.

I'm afraid we won't be rewriting the auth mechanism to look in both tables.
