### ISSUE TITLE
Send password reset to alternative email too

### ISSUE THREAD

**Issue by pierreozoux** [opensolutions/ViMbAdmin#210]
Given I've lost my pasword,
And I have an alternate email filled in,
When I ask for a password reset, I expect to receive it also on my alternative email.
(As I don't access my mailbox anymore)

**Comment by barryo** [comment]
Lost password facility is for administrators, not mailbox users. 

Mailbox users only have the facility to change their password. They need to goto their administrators for a password reset. Yes, not ideal, but that is as far as we have gone on this 😢
