### ISSUE TITLE
Add alias: address --> goto address validation

### ISSUE THREAD

**Issue by nine** [opensolutions/ViMbAdmin#213]
In the form /vimbadmin/alias/add
it is possible to enter the same address in the fields address and goto, 
e.g. address:foo@example.com --> goto:foo@example.com.
After adding this alias-loop it is not shown in the alias-table and therefore it is not possible to delete this loop anymore.

**Comment by barryo** [comment]
> it is possible to enter the same address in the fields address and goto,

yes, this is intentional. It allows you to alias you address but also retain mailbox delivery.

> After adding this alias-loop it is not shown in the alias-table and therefore it is not possible to delete this loop anymore.

There's a toggle button on the top left to show mailbox aliases.

**Comment by barryo** [comment]
Err, top right even.

**Comment by nine** [comment]
Thank you!
