### ISSUE TITLE
GUI dont works

### ISSUE THREAD

**Issue by MariusXYZ** [opensolutions/ViMbAdmin#215]

**Comment by dereckson** [comment]
@MariusXYZ Could you provide more context?

Do you experience a blank output? If so, this could be a general issue about how to serve a PHP application. Logs from your web server are useful in such cases.

If not, can you identify something you wish to do (aka an expected result) and what happens instead (aka the actual result)?

**Comment by barryo** [comment]
No further info provided -> closing.
