### ISSUE TITLE
Create Mailbox Error

### ISSUE THREAD

**Issue by Tortschi** [opensolutions/ViMbAdmin#220]
ViMbAdmin_Exception

File
    /srv/vimbadmin/library/ViMbAdmin/Dovecot.php
Line
    57
Message
    Error executing Dovecot password command: /usr/bin/doveadm pw -s 'SHA512-CRYPT' -u 'b.binder@vloggs.me' -p 'qYMfWjBmAvBHF19rO2RkCqqf'
Code
    0

Trace

#0 /srv/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Auth/Password.php(97): ViMbAdmin_Dovecot::password('SHA512-CRYPT', 'qYMfWjBmAvBHF19...', 'b.binder@vloggs...')
#1 /srv/vimbadmin/application/controllers/MailboxController.php(317): OSS_Auth_Password::hash('qYMfWjBmAvBHF19...', Array)
#2 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): MailboxController->addAction()
#3 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#4 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#6 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#7 /srv/vimbadmin/public/index.php(34): Zend_Application->run()
#8 {main}

Whats wrong? Hope anyone can help me.

**Comment by stephtr** [comment]
I also received that error even though the command itself can be executed fine (and returns the crypted password).
An alternative is to use PHP's SHA512 in application.ini:
`defaults.mailbox.password_scheme = "crypt:sha512"`

**Comment by ErikFL** [comment]
Same here, dovecot seemed to hash sha512 and sha256 fine through the command line but didn't work through vimbadmin. Any ways thanks @stephtr your workaround worked for me.

**Comment by barryo** [comment]
Linking to #178 where this can be addressed.
