### ISSUE TITLE
Notice: Use of undefined constant DS - assumed 'DS'

### ISSUE THREAD

**Issue by nysander** [opensolutions/ViMbAdmin#221]
On plain installation before turning off error display I got this error. Vimbadmin 3.0.15

    Notice: Use of undefined constant DS - assumed 'DS' in /usr/local/nonpublic_html/vimbadmin/library/ViMbAdmin/Smarty/functions/modifier.date_formatter.php on line 47

**Comment by dannoe** [comment]
It's already fixed: #217

**Comment by nysander** [comment]
ok :)
