### ISSUE TITLE
VimbAdmin PHP 5.6 to PHP 7

### ISSUE THREAD

**Issue by montymotz** [opensolutions/ViMbAdmin#228]
Hello,

after the update to version PHP 7 i get the following error:

`Warning: is_readable(): open_basedir restriction in effect. File(/usr/share/php//srv/vimbadmin/application/../library/ViMbAdmin/Resource/Auth.php) is not within the allowed path(s): (/usr/share/nginx/mail/:/tmp/:/usr/share/nginx/mail/admin/:/srv/vimbadmin/) in /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Loader.php on line 186`

and

`Fatal error: Uncaught Error: Class 'Memcache' not found in /srv/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Doctrine2cache.php:104 Stack trace: #0 /srv/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Doctrine2.php(95): OSS_Resource_Doctrine2cache->getDoctrine2cache() #1 /srv/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Doctrine2.php(62): OSS_Resource_Doctrine2->getDoctrine2() #2 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(695): OSS_Resource_Doctrine2->init() #3 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(638): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('doctrine2') #4 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('doctrine2') #5 /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.ph in /srv/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Doctrine2cache.php on line 104`

**Comment by barryo** [comment]
Hi @montymotz - probably an issue more suited to the mailing list but:

1. open_basedir is a [PHP security](http://php.net/manual/en/ini.core.php#ini.open-basedir) setting and it's not related to PHP7 specifically or ViMbAdmin. Looking at this part of the error:

```
File(/usr/share/php//srv/vimbadmin/application/../library/ViMbAdmin/Resource/Auth.php) is not within the allowed path(s)
```

it looks like a PHP configuration issue.

2. `Fatal error: Uncaught Error: Class 'Memcache' not found`

You do not mention which operating system you're using but on, say, Ubuntu, this is solved with `apt install php-memcache` (note that it's memcache and not memcache**d** that is required.

**Comment by Saulgodman** [comment]
Debian Jessie.

memcache is already installed

**Comment by barryo** [comment]
Hi @Saulgodman - you need this PHP extension:

http://php.net/manual/en/book.memcache.php

On Ubuntu, it's install with: `apt install php-memcache`

I don't know if the same applies to Debian Jessie. You can work around it by changing this line in `application/configs/application.ini`:

```
resources.doctrine2cache.type                    = 'MemcacheCache'
```

to

```
resources.doctrine2cache.type                    = 'ArrayCache'
```

but it may slow things down.
