### ISSUE TITLE
Broken jquery libs (Security)

### ISSUE THREAD

**Issue by drwetter** [opensolutions/ViMbAdmin#232]
_The library jquery-ui-dialog version 1.10.4 has known security issues. 
https://github.com/jquery/api.jqueryui.com/issues/281
https://snyk.io/vuln/npm:jquery-ui:20160721
The vulnerability is affecting all versions prior 1.12.0 (between * and 1.12.0)_

_The library jquery-migrate version 1.2.1 has known security issues.
http://bugs.jquery.com/ticket/11290
http://research.insecurelabs.org/jquery/test/
The vulnerability is affecting all versions prior 1.2.2 (between * and 1.2.2)_

_The library jquery version 1.11.1 has known security issues.
https://github.com/jquery/jquery/issues/2432
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
The vulnerability is affecting all versions prior 1.12.0 (between 1.4.0 and 1.12.0)_

Retrieved via retire.js

**Comment by Shadowghost** [comment]
Can we just upgrade the packages locally?
