### ISSUE TITLE
Creating a mailbox with the same username where an alias exists leads to error

### ISSUE THREAD

**Issue by dalu** [opensolutions/ViMbAdmin#233]
Vimbadmin3.0.15

domain: example.com
user: webmaster
when an alias (or goto or forwarding entry) exists that would forward webmaster@example.com to othermail@test.com and you create a mailbox webmaster@example.com an error page is shown, something about developer mode being enabled and a sql error.

What should've happened:
either the alias being deleted and then the mailbox being created, aka check if exists,
or
a dialog asking if the existing mailbox alias should be deleted

**Comment by barryo** [comment]
Fixed in #260

**Comment by dalu** [comment]
I don't see a linked PR

**Comment by barryo** [comment]
It's the commit and yes, it's prettier.

Of the options:

> What should've happened:
> either the alias being deleted and then the mailbox being created, aka check if exists,

We cannot assume this is what the user wanted. Maybe they forgot the alias exists bit the alias exists for good reason?

> a dialog asking if the existing mailbox alias should be deleted

There's a chunk of additional code, if/else, branched required to make this work in an already complex piece of code. If you'd like to submit a PR that can make thsi work without tying ourselves up in knots, I'm happy to have a look.
