### ISSUE TITLE
Fatal error - Zend_Controller_Response_Exception -Cannot send headers

### ISSUE THREAD

**Issue by diashk** [opensolutions/ViMbAdmin#237]
I have installed the ViMnAdmin  on centos 7. 
I get the error below on all responses except of index.php . 
The GUI has no style and after except of creating the admin user I can't do any other action because I have no buttons and no styles.

<br />
<b>Fatal error</b>:  Uncaught exception 'Zend_Controller_Response_Exception' with message 'Cannot send headers; headers already sent in , line 0' in /path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php:323
Stack trace:
#0 /path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php(341): Zend_Controller_Response_Abstract-&gt;canSendHeaders(true)
#1 /path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php(768): Zend_Controller_Response_Abstract-&gt;sendHeaders()
#2 /path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(992): Zend_Controller_Response_Abstract-&gt;sendResponse()
#3 /path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front-&gt;dispatch()
#4 /path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap-&gt;run()
#5 /path/vimbadmin/public/index.php(34) in <b>/path/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Response/Abstract.php</b> on line <b>323</b><br />

**Comment by barryo** [comment]
Possibly related to PHP7 issues. If still a problem in v3.1 then reopen. Thanks.

**Comment by haveamission** [comment]
@diashk Did you find a solution to this at all?
