### ISSUE TITLE
[Feature Request] absence note

### ISSUE THREAD

**Issue by LeKev92** [opensolutions/ViMbAdmin#240]
Hey developers!

I have a really useful feature request for ViMbAdmin for being on vacations, or just out of office: 
absence note (mail)

Currently there is no pretty solution for ViMbAdmin available, why not? I think this could be useful for many people. So I think this would be fantastic.

I'm looking forward to hear from yours!

**Comment by barryo** [comment]
Hi @LeKev92 - I'm afraid I'm closing this as it's unlikely to be implemented in the near future.

Please refer to *Bugs and Feature Requests* section of: https://www.vimbadmin.net/support.php
