### ISSUE TITLE
an error when create alias for existing email with email which contains domain name 6 letters.

### ISSUE THREAD

**Issue by georgetarazevich** [opensolutions/ViMbAdmin#241]
Have an error when create alias for existing email with email which contains domain name 6 letters.
For example, existing email:  abc@qwerty.com  goto abc@com.qwerty
Error message: Invalid email address(es).

Environment:
  ViMbAdmin V3.0.3.
  Linux Ubuntu

**Comment by barryo** [comment]
Cannot reproduce, sorry. Tested multiple ways.
