### ISSUE TITLE
Email's subject translation

### ISSUE THREAD

**Issue by eachtime** [opensolutions/ViMbAdmin#242]
I saw that the php underscore function is used to set email's subject when sending credentials to a new account. Is there an easy way to translate email's subject without modifing sources? I can't find anything in the wiki.

**Comment by maysara** [comment]
@eachtime , I would say you can deploy a skin and create the custom text there, check https://github.com/opensolutions/OSS-Framework/wiki/Skinning-Views .

**Comment by maysara** [comment]
Indeed, this seems to be under controllers, unable to skin it.

**Comment by barryo** [comment]
This was just forward planning to an eventual i18n/l10n. Unfortunately i18n/l10n is a **massive** amount of work and not something we can undertake at this time.
