### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by gearoofficial** [opensolutions/ViMbAdmin#243]
Hello,

we are experiencing problems with out VimbAdmin.

We are unable to log in to our account. When we are typing in our email and password, it doesn’t show any error but won’t let us get into our dashboard. When I type in any other password, it shows an error that the password is incorrect. 

When trying to reset a password, it shows an error page.

Is there any way you can help out here?

**Comment by adambirds** [comment]
I have the same issue on a new install.
I have the following setup:

CentOS 7
Nginx with PHP 7.1
VimBAdmin installed to /srv/vimbadmin

@gearoofficial have you had any luck solving yourself yet?

**Comment by gearoofficial** [comment]
Hi @adambirds ,
no we didnt – we actually switched completely now!

**Comment by adambirds** [comment]
What are you using instead? @gearoofficial

**Comment by barryo** [comment]
Possibly related to PHP7 - 🤷‍♂️    If not fixed in 3.1 then please reopen.
