### ISSUE TITLE
mv/rename email (Feature Request)

### ISSUE THREAD

**Issue by maysara** [opensolutions/ViMbAdmin#244]
I wonder if it would be possible to have the  way to rename mailboxes and/or user without directly modifying the database. currently I modify the username/localpart in database and leave the maildir intact. but Ideally I'd be allowed "dangerous" changes to the mailbox, which (ideally) would rename the mailbox file/dir accordingly as well, and allow me to choose to leave a redirect/alias behind for example, the move of the maildir will need then separate intervention on the directory hierarchy.

**Comment by barryo** [comment]
This would require the retention of state (old and new) in the database so it could be executed later in scripts. This is quite a bit FR and not within our current plans or time. Contact me if this is something you want to fund commercially.
