### ISSUE TITLE
some fields in Directory Entry plugin will not disappear

### ISSUE THREAD

**Issue by maysara** [opensolutions/ViMbAdmin#246]
I've enabled the Directory entry plugin, and set the disabled elements I want to hide to true, from the ones i tried, Business Category and website would not go away.

I've tried to trace down where this should be disabled, and got to the call "$subform->prepare( $disabled );" in application/plugins/DirectoryEntry.php . but did not move forward yet.

**Comment by mattymatty97** [comment]
problems are here:

https://github.com/opensolutions/ViMbAdmin/blob/master/library/ViMbAdmin/Form/Mailbox/DirectoryEntry.php

BusinesCategory is written with two s in this file

and website is called

LabelledUri

**Comment by mattymatty97** [comment]
tmp fix for now is in config file

use

disabled_elements.BusinessCategory = true

and

disabled_elements.LabelledUri = true
