### ISSUE TITLE
Feature request: Ability to limit alias targets to local domains

### ISSUE THREAD

**Issue by hcsaustrup** [opensolutions/ViMbAdmin#247]
We're seeing a bunch of people forwarding their e-mail to service providers like Gmail by use of aliases. Google apparently dislikes this (we're seeing a lot of warnings about bulk emailing and our mail servers being rate limited and such), so it would be great to prohibit this by limiting alias targets/goto's to local-only domains. Perhaps with an additional whitelist of external domains.

**Comment by barryo** [comment]
He @hcsaustrup - this isn't a bad idea at all. Could be core or a plugin. Do you think this is something you could provide a PR for?

[closing pending PR / reply as this dates from 2018]
