### ISSUE TITLE
The system cannot send emails, settings ignored

### ISSUE THREAD

**Issue by NetRelay** [opensolutions/ViMbAdmin#25]
The system itself cannot send emails (e.g. by means of "Send Settings" button) because it open connection to port 25 and sends "EHLO localhost", instead of port 587 and a fqdn as a EHLO. Obviously:

Sep 26 08:37:44 mail3 postfix/smtpd[22477]: NOQUEUE: reject: RCPT from mail3[123.123.123.123]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=postmaster@domain.it to=test1@johndoe.com proto=ESMTP helo=<localhost>

This happens because of "smtpd_recipient_restrictions" in postfix main.cf file:
  "reject_non_fqdn_hostname"

Email should be sent through the submission port defined in master.cf

In application.ini I can read:

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; See: http://framework.zend.com/manual/en/zend.mail.smtp-authentication.html
;;
;; Ensure you have a working mail server configuration so the system can
;; send emails:
;;
resources.mailer.smtphost = "mail3.domain.it"
;resources.mailer.username = ""
;resources.mailer.password = "96"
;resources.mailer.auth     = ""
;resources.mailer.ssl      = ""
resources.mailer.port     = "587"

But it doesn't work…

What am I missing? What am I doing wrong?

TIA…

**Comment by vesl** [comment]
Hi, 
I guess have a solution.
I just commented this line resources.mailer.smtphost = "localhost"
So then vimbadmin send a mail from IP eg : 10.0.0.253
Then add your local IP in my_networks and permit_my_networks in helo restriction.
That's works :-)
