### ISSUE TITLE
access_restriction is too short

### ISSUE THREAD

**Issue by andyboeh** [opensolutions/ViMbAdmin#252]
I use the Access Restriction plugin a lot and ran out of space for the access_restriction field. For now, I manually changed the database, but IMHO it would make sense, to increase the column length from 100 to a higher number (I use 512 for now).

Further, if you run out of space for the access_restriction field, you do not get any warning. Setting the permission simply doesn't stick.

**Comment by barryo** [comment]
Hi @andyboeh - 100 is a lot. Are you using stuff outside the standard:

```
vimbadmin_plugins.AccessPermissions.type.SMTP  = "SMTP"
vimbadmin_plugins.AccessPermissions.type.IMAP  = "IMAP"
vimbadmin_plugins.AccessPermissions.type.POP3  = "POP3"
vimbadmin_plugins.AccessPermissions.type.SIEVE = "SIEVE"
```

**Comment by andyboeh** [comment]
Yes, I have about 20 different permissions defined as I built our entire authentication and authorization system around ViMbAdmin's database. I understand that that's not the primary intention of ViMbAdmin, so I'm fine with a custom solution as well.

**Comment by barryo** [comment]
Thanks @andyboeh - I think the customer work around is best here 😉
