### ISSUE TITLE
resetting and changing password not sending emails

### ISSUE THREAD

**Issue by maysara** [opensolutions/ViMbAdmin#254]
Greetings,

I'm unable to receive emails from the reset and change password forms (not by admin user, but by end users) ; i.e. auth/lost-password and auth/change-password . I cannot see errors in the php logs or the vimbadmin logs var/log/vimbadmin.log.

Changing the password from the the admin account works fine.

Any help/idea/suggestion how to debug this? or if this is indeed a bug. I could not find a configuration to control this?

**Comment by maysara** [comment]
Greetings @barryo, the form for  Forgotten Password / Password Reset function for admins works, but not for mailboxes; this was very confusing as the feature list suggest otherwise.

Assuming the passwords for Admin and Mailboxes use the same hash, will changing the  resources.auth.oss.entity = "\\Entities\\Admin" value to use Mailbox and implement the missing functions that are called on that entity from OSS/Controller/Trait/Auth.php and OSS/Controller/Action/Trait/Doctrine2User.php break stuff. I understand that the functions such as getEmail are not present on Mailbox, but when implemented, the password reset works for mailboxes, but then probably due to reuse of the code in Doctrine2User (or somewhere else; possibly based on that) the login of admins break.

Any suggestions how to go about this? how to dis-entangle them even if with a dirty hack...

**Comment by thomasseilund** [comment]
Greetings maysara,
Did you ever find a way for the mailbox users to reset their password?
Thanks

**Comment by maysara** [comment]
Greetings,

Had two options, either implement the changes above and have the webserver to rewrite the requests to two setups sharing the same database, or write an interface that changes the password in the backend directly.

I chose the later as changes from vimbadmin upstream will certainly break that workaround (unless it implents this feature/fixes this bug).

**Comment by barryo** [comment]
So password reset for end users is not actually implement. Just reset password when the password is know. I know, this sucks.

Contact me if this is something you or anyone wants to fund commercially.
