### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by benhartwich** [opensolutions/ViMbAdmin#257]
Hi,

I wonder if this software will be maintained any more? I switched from postfixadmin to this software, but it seems, that there will be no further development / maintaining. Would be great to know, what´s the current state.

**Comment by barryo** [comment]
It is maintained. I'm aware of a couple of outstanding issues which I hope to address in Jan. 

Note that maintained != planned new features. It's pretty much in a feature complete state.
