### ISSUE TITLE
Feature request: domain quota

### ISSUE THREAD

**Issue by benhartwich** [opensolutions/ViMbAdmin#258]
Hi,

is it somehow possible to set a domain quota? For example a domain administrator can handle 10GB quota to different mailboxes of his managed domain.

**Comment by maysara** [comment]
I'm not sure what you mean, but domain quota should be there, although you might want to take a look at #249

**Comment by barryo** [comment]
Implemented in a1eb0e154920fb01b923ebc9ccaf241b6b108a98
