### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by cwr10010** [opensolutions/ViMbAdmin#259]
Is this project still active? With PHP 7.0 being EOLed this codebase should be migrated to PHP 7.3. Is there anything planed alike?

**Comment by barryo** [comment]
It's active but stable. Works fine on php 7.2. Let me know if there's bugs in 7.3 but the changes between 7.2 and 7.3 are minimal so should be okay.

**Comment by cwr10010** [comment]
Good to know

I am getting compatibility warnings like
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /path/to/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
same about zend framework.
With the current round of updates in the linux distros 7.3 will be standard. Debian is probably next this summer.

**Comment by cwr10010** [comment]
To be more complete. These warnings appear ever since I moved to PHP 7.3

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /path/to/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /path/to/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 205

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 205
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 219

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 219
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 219

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 219
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 219

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php on line 219
Zend_Session_Exception Object
(
[_previous:Zend_Exception:private] => 
[message:protected] => Session must be started before any output has been sent to the browser; output started in /path/to/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php/2640
[string:Exception:private] => 
[code:protected] => 0
[file:protected] => /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session.php
[line:protected] => 456
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /path/to/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php
[line] => 143
[function] => start
[class] => Zend_Session
[type] => ::
[args] => Array
(
[0] => 1
)

)

[1] => Array
(
[file] => /path/to/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Namespace.php
[line] => 81
[function] => __construct
[class] => Zend_Session_Namespace
[type] => ->
[args] => Array
(
[0] => Application
)

)

[2] => Array
(
[file] => /path/to/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Namespace.php
[line] => 63
[function] => getSession
[class] => OSS_Resource_Namespace
[type] => ->
[args] => Array
(
)

)

[3] => Array

**Comment by huddx01** [comment]
same here after update to php 7.3 on debian...

`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? `

**Comment by Mindbuild** [comment]
1 of the library requirements given on the website: https://github.com/opensolutions/ViMbAdmin/wiki/Installation is mcrypt library. It was only available from PHP 5.4 through PHP 7.1. It was removed in PHP7.2. 
I'm running around 5 Vimbadmin servers on PHP 7.0/7.1, but now urgently need to upgrade the whole setup to PHP 7.3. It seems I don't have much options left except PostfixAdmin. With the prehistoric GUI of PostfixAdmin my clients would bash me for going backwards to dark ages. 
Is there any possibility that you just patch up the requirements for PHP 7.3 in a new release?

**Comment by huddx01** [comment]
Think so, too... Please update...

**Comment by kurim** [comment]
Temporary solution for those 3 warnings, just replace "continue" with "break"
/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php
Original:
```
if ( ! $associatedId) {
// Foreign key is NULL
$class->reflFields[$field]->setValue($entity, null);
$this->originalEntityData[$oid][$field] = null;
continue;
}
```
correction:
```
if ( ! $associatedId) {
// Foreign key is NULL
$class->reflFields[$field]->setValue($entity, null);
$this->originalEntityData[$oid][$field] = null;
break;
}
```
same for /vimbadmin/vendor/zendframework/zendframework1/library/Zend/Form.php line 1173
and /vimbadmin/vendor/zendframework/zendframework1/library/Zend/Form.php line 1690

**Comment by kaechele** [comment]
I just did this: https://github.com/kaechele/ViMbAdmin/tree/php-73
All this does is upgrade Doctrine to 2.6 and switch to a Zend Framework 1 fork that supports PHP 7.3.
Note that upgrading to Doctrine 2.6 will require at least PHP 7.1.
Haven't done extensive testing yet but it works fine (adding/editing/deleting mailboxes and domains) for me on PHP 7.3.6.
Haven't tested any upgrades (i.e. Doctrine database migrations), just fresh installs.

**Comment by fandisus** [comment]
Anybody else got these lines?

> PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
> 
>   [Doctrine\DBAL\Exception\DriverException]
>   An exception occured in driver: could not find driver
> 
>   [Doctrine\DBAL\Driver\PDOException]
>   could not find driver
> 
>   [PDOException]
>   could not find driver

My System:
Ubuntu 18.04
PHP 7.3.7
MySQL 5.7.26-0ubuntu0.18.04.1

**Comment by Mindbuild** [comment]
> I just did this: https://github.com/kaechele/ViMbAdmin/tree/php-73
> All this does is upgrade Doctrine to 2.6 and switch to a Zend Framework 1 fork that supports PHP 7.3.
> Note that upgrading to Doctrine 2.6 will require at least PHP 7.1.
> Haven't done extensive testing yet but it works fine (adding/editing/deleting mailboxes and domains) for me on PHP 7.3.6.
> Haven't tested any upgrades (i.e. Doctrine database migrations), just fresh installs.

Hi Felix,
Thank you for the upgrade. I'm trying to install your version, but haven't got any luck yet. I've tried:
/bin/composer.phar create-project kaechele/vimbadmin $INSTALL_PATH -s dev
But that command gives error: Could not find package kaechele/vimbadmin with stability dev.
I also tried manual copy paste etc. but that didn't work either. 
Can you please guide me how to install your version of Vimbadmin?

**Comment by Mindbuild** [comment]
> Hi Felix,
> Thank you for the upgrade. I'm trying to install your version, but haven't got any luck yet. I've tried:
> /bin/composer.phar create-project kaechele/vimbadmin $INSTALL_PATH -s dev
> But that command gives error: Could not find package kaechele/vimbadmin with stability dev.
> I also tried manual copy paste etc. but that didn't work either.
> Can you please guide me how to install your version of Vimbadmin?

Well I installed it using just the simple /bin/composer.phar install command. But now in the next command: ./bin/doctrine2-cli.php orm:schema-tool:create
I'm getting the following error:
PHP Fatal error:  Uncaught Error: Call to undefined function Doctrine\ORM\Mapping\Driver\simplexml_load_string() in /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php:848
Stack trace:
#0 /srv/vimbadmin/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(91): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMappingFile('/srv/vimbadmin/...')
#1 /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(60): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('Entities\\AliasP...')
#2 /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(151): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('Entities\\AliasP...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /srv/vimbadmin/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(304): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, in /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 848

May be I installed it wrongly. I'm still working on it, let's see if I can resolve it as well...

**Comment by kaechele** [comment]
Basically you just need to clone my git repo, switch to the php-73 branch on it and run composer install.
That should work unless I forgot any dependencies the newer Doctrine ORM version may require.

**Comment by Mindbuild** [comment]
> 
> 
> Basically you just need to clone my git repo, switch to the php-73 branch on it and run composer install.
> That should work unless I forgot any dependencies the newer Doctrine ORM version may require.
Thank you very much for your reply. Please pardon my ignorance on the subject.
Here's what I'm doing:
mkdir /root/vimbadmin-git/
cd /root/vimbadmin-git/
git clone https://github.com/kaechele/ViMbAdmin.git
cd ViMbAdmin
git branch -a
git checkout php-73
/bin/composer.phar install
...
./bin/doctrine2-cli.php orm:schema-tool:create
PHP Fatal error:  Uncaught Error: Call to undefined function Doctrine\ORM\Mapping\Driver\simplexml_load_string() in /root/vimbadmin-git/ViMbAdmin/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php:848
...
I've tried to manually copy/rename the installed folder ViMbAdmin to another place etc. But the same error repeats. I'm on Debian 9.

**Comment by kaechele** [comment]
Looks like you're missing a module for PHP.
I don't use any Debian based distro but a quick Google search tells me you're probably missing the package php-xml (and potentially more than that, I don't exactly know which PHP-level dependencies ViMbAdmin has).

**Comment by Mindbuild** [comment]
> 
> 
> Looks like you're missing a module for PHP.
> I don't use any Debian based distro but a quick Google search tells me you're probably missing the package php-xml (and potentially more than that, I don't exactly know which PHP-level dependencies ViMbAdmin has).

You're correct I was missing a PHP module. Actually I started this install on a server already running PostfixAdmin and it just got out of my mind that I needed extra PHP modules to make Vimbadmin work. 

Thanks to you, it's working perfectly on PHP 7.3. It has been for so long that I had been looking for a solution to this and you solved it, not just for me, but for many looking for a fix to this issue.

Kind regards,

M. F. Faruqi

**Comment by rootwyrm** [comment]
Can we please get some attention on updating to PHP7.3 support with Doctrine 2.6 and the new official zendframework?

**Comment by kaechele** [comment]
Check out my comment above with a link to a workaround in my fork.
Moving this to the latest Zend Framework technically constitutes a rewrite, so I wouldn't hold my breath for that to happen.

**Comment by kr1pt0ph0b14** [comment]
I got same problems as others above. I wish the dev could update it for PHP 7.3 :/

**Comment by cwr10010** [comment]
Maybe the update of Felix can be merged here? @kaechele Did you do a pull request on this?

**Comment by Betalord** [comment]
Any updates on this? Is project completely abandoned or will get updated in some near future? PostfixAdmin is being actively worked on, so I guess I'll use that for now, but ViMbAdmin looks just so much nicer. Ah well.

**Comment by hcsaustrup** [comment]
Agreed - VIMbAdmin is downright delicious, where as PostfixAdmin seems terribly outdated UI-wise. Personally, I'm trying to find an OpenLDAP UI and run everything from there now.

**Comment by yodatak** [comment]
Feel like its time to fork it :/

**Comment by barryo** [comment]
Hi all. 

We are delighted to announce the immediate release and availability of ViMbAdmin v3.1.0.

This release supports all versions of PHP up to and including 7.4 (latest at time of writing).

This is a long awaited and requested update and we apologise for the delay. Sincerely apologise in fact. This project is not dead by anymeans - just life and work gets in the way 😢  

In terms of future work - from a feature perspective, ViMbAdmin v3 is pretty much feature complete in my eyes. It does what we intended and require it to do. We'd look to do a complete modern rewrite for any future features I imagine. I'm considering what that should look like right now.

I'd like to give a special shoutout to @Shardj who's shardj/zf1-future fork of the long EOL'd Zend Framework v1 made this possible.

I'll close this now. Follow up here if relevent and I'll come back with reponses. Please open new issues for any problems with v3.1.0.
