### ISSUE TITLE
Doctrine\DBAL\Exception\UniqueConstraintViolationException

### ISSUE THREAD

**Issue by k3simha** [opensolutions/ViMbAdmin#260]
How to get rid of this error??

File
/usr/local/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php

Line
66

Message
An exception occurred while executing 'INSERT INTO alias (address, goto, active, created, modified, Domain_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["mail@k3simha.xyz", "mail@k3simha.xyz", 1, "2019-05-30 16:26:15", null, "1"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'mail@k3simha.xyz' for key 'UNIQ_E16C6B94D4E6F81'

Code
0

Trace
#0 /usr/local/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /usr/local/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(174): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO ali...', Array)
#2 /usr/local/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\DBAL\Statement->execute()
#3 /usr/local/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(966): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
#4 /usr/local/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /usr/local/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(340): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /usr/local/vimbadmin/application/controllers/MailboxController.php(360): Doctrine\ORM\EntityManager->flush()
#7 /usr/local/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): MailboxController->addAction()
#8 /usr/local/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /usr/local/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/local/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/local/vimbadmin/public/index.php(34): Zend_Application->run()
#13 {main}

**Comment by maysara** [comment]
don't try to forward email to itself, don't use the same alias for two emails ...etc ; I don't think this is really a bug ...
