### ISSUE TITLE
Documentation of vimbtool.php

### ISSUE THREAD

**Issue by MasinAD** [opensolutions/ViMbAdmin#261]
Is there any documentation available which actions are possible with `bin/vimbtool.php`?

For automation purposes I'm looking for a way to create mailboxes and aliases in ViMBAdmin using the command line. `vimbtool.php` looked promising but it seems there are only the four actions available which are called in the cronjob.

**Comment by barryo** [comment]
Hi @MasinAD - the only actions available are those that are part of the documentation via cronjob.

There is no API in ViMbAdmin but the database schema is really simple so you should be able to create automtaion by just adding / editing the database directly.
