### ISSUE TITLE
OpenSMTPD ?

### ISSUE THREAD

**Issue by sachaz** [opensolutions/ViMbAdmin#263]
Is any plan or documentation to make it work with OpenSMTPD ?

**Comment by barryo** [comment]
Hi @sachaz - no plans for this because I am not familiar with it. ViMbAdmin is a database frontend so if OpenSNMPD can be made work with the schema, there should be no problem. Happy to accept any documentation on this if you get it working.

**Comment by sachaz** [comment]
Hi @barryo 
as Postfix, OpenSMTPD can use Mysql, Redis, LDAP... 
https://github.com/OpenSMTPD/OpenSMTPD-extras/tree/master/extras/tables/table-mysql

- /etc/smtpd.conf

```
(...)
table vdomains mysql:/etc/smtpd-mysql.conf
table vusers mysql:/etc/smtpd-mysql.conf
table userinfo mysql:/etc/smtpd-mysql.conf
table credentials mysql:/etc/smtpd-mysql.conf
```

- /etc/smtpd-mysql.conf

```
host localhost
username opensmtpd
password MA-SUPER-PASSPHRASE
database smtpd
query_credentials SELECT user,password FROM userinfo WHERE user=?;
query_domain SELECT domain FROM vdomains WHERE domain=? LIMIT 1;
query_userinfo SELECT uid,gid,maildir FROM userinfo where user=?;
query_alias SELECT alias FROM valias WHERE addr=?;
```
