### ISSUE TITLE
Dovecot saying "Not a valid MD5-CRYPT or PLAIN-MD5 password" (log in with Roundcube)

### ISSUE THREAD

**Issue by Betalord** [opensolutions/ViMbAdmin#266]
I'm having the following problem: I've set up ViMbAdmin more or less as the docs say, and all works (I add domains, mailboxes etc.), but when I try to login via Roundcube, it just doesn't work (login failed). If I look at the logs, this is what I get from dovecot (/var/log/mail.log):

`May 18 12:48:40 betalord dovecot: auth-worker(1709475): Error: sql(betalord@betalord.com,127.0.0.1,<GyrF5+ml+Jx/AAAB>): Invalid password in passdb: Not a valid MD5-CRYPT or PLAIN-MD5 password
`

Any idea what's wrong?

**Comment by Marcwa19197** [comment]
Which settings are you using as "defaults.mailbox.password_scheme" in your application.ini? (Installpath/application/configs/application.ini)

**Comment by Betalord** [comment]
I resolved the problem with help of good folks at freenode IRC. There were several things that did not work with my configuration, to be honest. Anyway, I resolved my problem, thanks anyway!
