### ISSUE TITLE
version not bumped

### ISSUE THREAD

**Issue by eilandert** [opensolutions/ViMbAdmin#267]
Thanks for creating an update!

However, the version is not bumped from 3.1.1 to 3.2.0, and now the webui complains from time to time that there is an update.

**Comment by dalu** [comment]
hotifx:
https://github.com/opensolutions/ViMbAdmin/blob/master/library/ViMbAdmin/Version.php#L49

change to
`    const VERSION = '3.2.0';`

**Comment by plittlefield** [comment]
Hi,

I tried...

```
$ git pull
Already up to date.
```
so my web interface says...

`Current version is: 3.1.1. There is a new version available: 3.2.0. See the releases list. `

...what am I doing wrong?

:-)

Paully

**Comment by barryo** [comment]
@dalu 's hotfix will work fine.

We've also just fixed this in [v3.2.1](https://github.com/opensolutions/ViMbAdmin/releases/tag/3.2.1). That's the only change.
