### ISSUE TITLE
alias editing : error

### ISSUE THREAD

**Issue by Rico29** [opensolutions/ViMbAdmin#268]
Hello
I'm using master branch

I get an error when editing an email alias : 
URL : https://vimbadmin.xxx.fr/alias/edit/alid/114
error : Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/share/vimbadmin/application/Proxies/__CG__EntitiesDomain.php on line 49

It seems that this syntax is not valid : 
```
# sed -n 49p /usr/share/vimbadmin/application/Proxies/__CG__EntitiesDomain.php 
    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
```
removing the "?" seems OK, and I don't get the error anymore : 
```
# sed -n 49p /usr/share/vimbadmin/application/Proxies/__CG__EntitiesDomain.php 
    public function __construct(\Closure $initializer = null, \Closure $cloner = null
```

Will propose a PR for that.

**Comment by Rico29** [comment]
This breaks vimbadmin in php5. works in php7

**Comment by barryo** [comment]
Thanks @Rico29. I think in 2022 we don't need to worry about PHP5 anymore really.
