### ISSUE TITLE
Archiving stuck

### ISSUE THREAD

**Issue by mschluepmann** [opensolutions/ViMbAdmin#271]
Hello,

I set several e-mail accounts to be archived. The archiving process was not finished successful due to a database timeout. All e-mail accounts which have to be a archived are stuck in the state _Archiving_ now.

There seem to be two issues here: First, long running archiving functions due to large e-mail accounts loose their database connection. Second, if an archiving task did not finish correctly it is stuck in the state _Archiving_.

How can I solve this and  continue/finish the archiving process?

Regards,
Marc

**Comment by barryo** [comment]
Time out closing on this - please reopen if help still required.
