### ISSUE TITLE
Lost Password Captcha not shown

### ISSUE THREAD

**Issue by simarilius** [opensolutions/ViMbAdmin#272]
The Reset Password Page doesn't shows a Captcha.

Warning: imageftbbox(): Could not find/open font in /lynn/vimbadmin/pub/vendor/shardj/zf1-future/library/Zend/Captcha/Image.php on line 507

Warning: imagefttext(): Could not find/open font in /lynn/vimbadmin/pub/vendor/shardj/zf1-future/library/Zend/Captcha/Image.php on line 510

I fixed it by adding a directory and the font to /lynn/vimbadmin/pub/data/font/freeserif.ttf

I also had to change the path in library/OSS/Captcha/Image.php:

   if( strpos( dirname( __FILE__ ), 'src/' ) === false )
            **$font = dirname( __FILE__ ) . '/../../../data/font/freeserif.ttf';**
        else
            $font = dirname( __FILE__ ) . '/../../../data/font/freeserif.ttf';

**Comment by bradley-jarvis** [comment]
I had the same problem with pretty much the same fix, I put the font file where it was looking for it though so didn't need to change any code

**Comment by alainwolf** [comment]
My workaround on fresh Ubuntu 20.04 server:

    sudo apt install fonts-freefont-ttf
    sudo -u www-data mkdir -p library/data/font
    sudo -u www-data  ln -s /usr/share/fonts/truetype/freefont/FreeSerif.ttf library/data/font/freeserif.ttf
