### ISSUE TITLE
ViMbAdmin not logging out correctly with Firefox.

### ISSUE THREAD

**Issue by skitchin** [opensolutions/ViMbAdmin#273]
I'm wondering if this is Firefox related issue since logging out from Vimbadmin on Chrome and Safari works okay.  I'm using Vibadmin 3.2.1 and I didn't have Firefox issues with 3.0.15 before upgrading to 3.2.1.

**Comment by barryo** [comment]
I'm pretty satisfied that this is not a ViMbAdmin issue.
