### ISSUE TITLE
Problem with Zend

### ISSUE THREAD

**Issue by bc-bjoern** [opensolutions/ViMbAdmin#275]
Hi, 

i can't get it running again. 

` Fatal error: Uncaught Zend_Application_Bootstrap_Exception: Unable to resolve plugin "auth"; no corresponding plugin with that name in /usr/share/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php:340 Stack trace: #0 /usr/share/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(392): Zend_Application_Bootstrap_BootstrapAbstract->getPluginResource('auth') #1 /usr/share/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(404): Zend_Application_Bootstrap_BootstrapAbstract->getPluginResources() #2 /usr/share/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(637): Zend_Application_Bootstrap_BootstrapAbstract->getPluginResourceNames() #3 /usr/share/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('dbautoforsessio...') #4 /usr/share/vimbadmin/vendor/shardj/zf1-fut in /usr/share/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php on line 340
`

I'm on a CentOS 7.8 and the composer installation was running fine. Any Idea what I can do now?

**Comment by quorumini** [comment]
hey bc-bjoern,

i had the same problem and stumbeld upon changed paths in my vimbadmin/application/configs/application.ini
had to change following paths:

was:
pluginPaths.OSS_Resource = APPLICATION_PATH "/../vendor/opensolutions/oss-framework/src/OSS/Resource"

is:
pluginPaths.OSS_Resource = APPLICATION_PATH "/../library/OSS/Resource"

and smarty

was:
resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/opensolutions/oss-framework/src/OSS/Smarty/functions"

is:
resources.smarty.plugins[] = APPLICATION_PATH "/../library/OSS/Smarty/functions"

hope this helps

**Comment by barryo** [comment]
Thanks @quorumini and you're correct. This was also covered in these release notes: https://github.com/opensolutions/ViMbAdmin/releases/tag/3.2.0
