### ISSUE TITLE
Fatal error: Uncaught SmartyException: prefilter 'whitespace_control' not found or callable

### ISSUE THREAD

**Issue by AlexGnatko** [opensolutions/ViMbAdmin#276]
I was updating an old ViMbAdmin installation and ran into this problem:

Fatal error: Uncaught SmartyException: prefilter 'whitespace_control' not found or callable...

I tried to re-install again from scratch and still have the same results.

**Comment by AlexGnatko** [comment]
OK, I've found the solution myself.

INI file again:

`resources.smarty.plugins[] = APPLICATION_PATH "/../library/OSS/Smarty/functions"`

used to be:

`resources.smarty.plugins[] = APPLICATION_PATH "/../vendor/opensolutions/oss-framework/src/OSS/Smarty/functions"
`

**Comment by barryo** [comment]
Hi @AlexGnatko - probably these release notes will help:

https://github.com/opensolutions/ViMbAdmin/releases/tag/3.2.0
