### ISSUE TITLE
Feature Request: 2FA

### ISSUE THREAD

**Issue by eilandert** [opensolutions/ViMbAdmin#281]
Since the administrator logins have access to sensitive data I would like an option for 2FA 

Looking at a roundcube plugin it can be done for TOTP/HOTP/Yubikey with

$ composer require "endroid/qrcode" "~1.5.0" --no-update
$ composer require "spomky-labs/otphp" "~5.0.0" --no-update
$ composer require "enygma/yubikey" "~3.2"

**Comment by barryo** [comment]
Hi @eilandert - currently we have no plans for 2FA. I certainly know and appreciate the importance of it but it's a chunk of work. Happy to review PRs that support 2FA to the extent of:

* 2fa a working option on login
* admins can enable / disable 2fa on their own and other's accounts
