### ISSUE TITLE
Issue whilke Database Creation

### ISSUE THREAD

**Issue by Vaibhav4697** [opensolutions/ViMbAdmin#284]
I have been following the steps and when I am trying to create the database with the command below, it throwing me such error.

Database Creation
Now that your configuration is set and you have setup a database and user in MySQL, you need to create the database schema:

cd $INSTALL_PATH
./bin/doctrine2-cli.php orm:schema-tool:create

Error:
![image](https://user-images.githubusercontent.com/30215969/161102359-580615dc-9e5a-405c-9144-73cf6ffa8f52.png)
Can you please give it a look, what is it about?

**Comment by Vaibhav4697** [comment]
Yeah, I know that but I have granted all the permission to this user in mysql and I have also verified the password many times.

**Comment by barryo** [comment]
In your `application.ini` file, you'll have config like:

```
resources.doctrine2.connection.options.driver   = 'pdo_mysql'
resources.doctrine2.connection.options.dbname   = 'vimbadmin'
resources.doctrine2.connection.options.user     = 'vimbadmin'
resources.doctrine2.connection.options.password = 'password'
resources.doctrine2.connection.options.host     = 'localhost'
```

Taking these exactly as they are and on the same server as ViMbAdmin, this should work:

```
mysql -h localhost -u vimbadmin -ppassword vimbadmin
```
