### ISSUE TITLE
extends possibilities for plugin

### ISSUE THREAD

**Issue by micdech** [opensolutions/ViMbAdmin#286]
Hi all, is there in program to extends possibilities for plugins?

Can't see any hooks for domains, and i want to try to write a plugin for opendkim.

Anyone wants to help me or find a way to do that?

**Comment by PhrozenByte** [comment]
See https://github.com/opensolutions/ViMbAdmin/wiki/Plugins

The domain events are missing in the wiki, but there's quite a number of domain events you can hook into. Events are triggered using `$this->notify()` in [`DomainController`](https://github.com/opensolutions/ViMbAdmin/blob/master/application/controllers/DomainController.php) (e.g. the [`domain_add_addPostflush` event](https://github.com/opensolutions/ViMbAdmin/blob/6fc7b6a7be3eb9264b27caf4e48d8c90bafc3ce9/application/controllers/DomainController.php#L228)), simply check ViMbAdmin's code. There are separate events for adding (includes edits) and deleting (purging) a domain. If you need more events, you might simply add them and open a pull request - even though the project isn't as active as it used to be. There are more events for mailboxes and aliases, check their respective controller classes. Also see [`application/plugins/`](https://github.com/opensolutions/ViMbAdmin/tree/master/application/plugins) for existing plugins; you might simply use one of them as a basis.
