### ISSUE TITLE
Database column `mailbox`.`username` is not unique

### ISSUE THREAD

**Issue by PhrozenByte** [opensolutions/ViMbAdmin#289]
`mailbox`.`username` currently isn't required to be unique in the database (uniqueness is currently only [enforced by code](https://github.com/opensolutions/ViMbAdmin/blob/6fc7b6a7be3eb9264b27caf4e48d8c90bafc3ce9/application/controllers/MailboxController.php#L282-L290)), nor is the column even indexed. Querying the ViMbAdmin database using `mailbox`.`username` as (supposed to be unique) identifier is one of the main database queries any mail server software (Dovecot, Postfix, etc.) performs frequently (up to thousands of queries a day, depending on the number of users). `mailbox`.`local_part` should be indexed, too.

**Comment by barryo** [comment]
Good catch. Fixed in 5836ad571a5017351605a341c1a3c5c02e348e3c and can be updated via:

```
# sanity check the output of:
./bin/doctrine2-cli.php orm:schema-tool:update --dump-sql

# and then run:
./bin/doctrine2-cli.php orm:schema-tool:update --force
```
