### ISSUE TITLE
Ensure a checkout contains the version number of vimbadmin

### ISSUE THREAD

**Issue by frlan** [opensolutions/ViMbAdmin#294]
I was just on my way updating an elderish version of vimabadmin and trying to figure out which exact version there was installed. It would be easier to include the version in an obvious place inside the release tarball.

**Comment by PhrozenByte** [comment]
Check [`library/ViMbAdmin/Version.php`](https://github.com/opensolutions/ViMbAdmin/blob/master/library/ViMbAdmin/Version.php).

**Comment by frlan** [comment]
Sure -- I can search the sources for. But it would make more sense to keep it somewhere in /

**Comment by barryo** [comment]
It looks like you found it which is great. I'm not going to move this around at this point in the lifetime of the app as it'll probably confuse the existing user base.
