### ISSUE TITLE
Update UPDATING with recent changes needs to be done for 3.x branch

### ISSUE THREAD

**Issue by frlan** [opensolutions/ViMbAdmin#295]
Last content is 
```

Specific Update Notes
======================

Upgrading from 0.1.2 and below to 2.0 and above
------------------------------------------------
```

Grabbing these informations from release notes is … hard. It would be cool if there would be the needed information documented, too.

**Comment by barryo** [comment]
Thanks for pointing that out @frlan  - now changed to reference: https://github.com/opensolutions/ViMbAdmin/wiki/Updating
