### ISSUE TITLE
Number of mailboxes = 1 when there are 150

### ISSUE THREAD

**Issue by itabv** [opensolutions/ViMbAdmin#300]
I installed postifx and vimbadmin and imported the mailboxes from the old mail server (mysqldump mysqlimport) into the mariadb database. But the mailbox counter remained equal to 1. If i go to the list of mailboxes, then they are all there (159) and the mail works fine. But the counter of the number of boxes does not increase. This is the only problem. But the counter increases if I create mail through the vimbadmin web interface.

![image](https://user-images.githubusercontent.com/116759389/216836728-18480941-ab2c-4dca-ba7a-13fd95fabab6.png)

![image](https://user-images.githubusercontent.com/116759389/216836836-7a44719f-5c74-4036-873a-58110cda8674.png)

**Comment by nine** [comment]
Please check if you are using a supported PHP version. See also #301.

**Comment by itabv** [comment]
Right now I'm using php.8.1 and still I have this problem
