### ISSUE TITLE
vimbtool.php -a mailbox.cli-get-sizes not working with php 8.2

### ISSUE THREAD

**Issue by sm4rty-github** [opensolutions/ViMbAdmin#303]
vimbtool.php -a mailbox.cli-get-sizes

throws:
` 
./bin/vimbtool.php -a mailbox.cli-get-sizes
PHP Deprecated:  Creation of dynamic property Bootstrap::$frontController is deprecated in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Resource/Frontcontroller.php on line 161

Deprecated: Creation of dynamic property Bootstrap::$frontController is deprecated in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Resource/Frontcontroller.php on line 161
PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 211

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 211
PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 226

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 226
PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 226

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 226
PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 226

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php on line 226
Zend_Session_Exception Object
(
    [message:protected] => Session must be started before any output has been sent to the browser; output started in /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Resource/Frontcontroller.php/161
    [string:Exception:private] =>
    [code:protected] => 0
    [file:protected] => /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session.php
    [line:protected] => 466
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Session/Namespace.php
                    [line] => 143
                    [function] => start
                    [class] => Zend_Session
                    [type] => ::
                )

            [1] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/library/OSS/Resource/Namespace.php
                    [line] => 81
                    [function] => __construct
                    [class] => Zend_Session_Namespace
                    [type] => ->
                )

            [2] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/library/OSS/Resource/Namespace.php
                    [line] => 63
                    [function] => getSession
                    [class] => OSS_Resource_Namespace
                    [type] => ->
                )

            [3] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php
                    [line] => 695
                    [function] => init
                    [class] => OSS_Resource_Namespace
                    [type] => ->
                )

            [4] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php
                    [line] => 638
                    [function] => _executeResource
                    [class] => Zend_Application_Bootstrap_BootstrapAbstract
                    [type] => ->
                )

            [5] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php
                    [line] => 598
                    [function] => _bootstrap
                    [class] => Zend_Application_Bootstrap_BootstrapAbstract
                    [type] => ->
                )

            [6] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application.php
                    [line] => 389
                    [function] => bootstrap
                    [class] => Zend_Application_Bootstrap_BootstrapAbstract
                    [type] => ->
                )

            [7] => Array
                (
                    [file] => /var/www/domain.tld/vimbadmin/bin/vimbtool.php
                    [line] => 45
                    [function] => bootstrap
                    [class] => Zend_Application
                    [type] => ->
                )

        )

    [previous:Exception:private] =>
    [_previous:Zend_Exception:private] =>
)
`

**Comment by nine** [comment]
duplicate with #301
