### ISSUE TITLE
RoundCube Plugin

### ISSUE THREAD

**Issue by bschmitt** [opensolutions/ViMbAdmin#83]
I'm wondering what this *vimbadmin_plugins.RoundCube.disabled = true* is about?

Is there a RoundCube Plugin planned or somewhere available? What will be the features?

**Comment by TheAcastus** [comment]
Yeah guys, I am trying to configure RoundCube and ViMbAdmin, and I have too many troubbles with it and still not working together.. :(

**Comment by pierreozoux** [comment]
anybody found his way?

**Comment by theofidry** [comment]
Why closing it @barryo?

**Comment by barryo** [comment]
Because the the development of this was tied to a project that didn't proceed a couple of years ago. No progress is planned I'm afraid.

**Comment by theofidry** [comment]
Then shouldn't all reference to the roundcube plugin be removed?

**Comment by barryo** [comment]
Good point... one sec...

**Comment by TheAcastus** [comment]
Well, then it is solved. Not how I expect but, yep.It is done. Time to make my own mail :D

**Comment by gonzzor** [comment]
What about the roundcube config in application/config/?

**Comment by PhrozenByte** [comment]
@TheAcastus, I think a PR for making the RoundCube plugin work is highly appreciated (personally I'd love to see that, too) :smiley:

**Comment by barryo** [comment]
> What about the roundcube config in application/config/?

@gonzzor config? what config :innocent:

**Comment by barryo** [comment]
What exactly would a RoundCube plugin do? *(I know what out very application/customer specific one was intended to do, just wondering what people were expecting here?)

**Comment by gonzzor** [comment]
> What about the roundcube config in application/config/?
> 
> @gonzzor config? what config 
> 
The one you removed in 06321dd. I must have viewed an older revision :)

**Comment by barryo** [comment]
> The one you removed in 06321dd. I must have viewed an older revision :)

I was just joking @gonzzor :wink:
