### ISSUE TITLE
vimbadmin 3.x - unable to create database tables

### ISSUE THREAD

**Issue by wdetter** [opensolutions/ViMbAdmin#93]
Hi everybody, 

trying to set up latest version from git, stuck during creation of tables: 

root@mail:/var/www/vimbadmin# ./bin/doctrine2-cli.php orm:schema-tool:create
PHP Notice:  Undefined index: doctrine2 in /var/www/vimbadmin/bin/utils.inc on line 80
PHP Notice:  Undefined index: doctrine2cache in /var/www/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Resource/Doctrine2.php on line 88
ERROR: Doctrine2 requires Doctrine2Cache to have been already bootstrapped

Regards,
Werner

**Comment by fandisus** [comment]
Hi. I am on ubuntu 18.04, with PHP 7.3.7, MySQL 5.7.26. I followed the instruction, but end up with some warning and "could not find driver" error messages.

> PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
> 
> 
>   [Doctrine\DBAL\Exception\DriverException]
>   An exception occured in driver: could not find driver
> 
> 
> 
>   [Doctrine\DBAL\Driver\PDOException]
>   could not find driver
> 
> 
> 
>   [PDOException]
>   could not find driver
> 
> 
> orm:schema-tool:create [--dump-sql]
> 

Got suggestion?

**Comment by barryo** [comment]
@fandisus - this looks like you don't have php-mysql installed.
