### ISSUE TITLE
DKIM

### ISSUE THREAD

**Issue by almereyda** [opensolutions/ViMbAdmin#97]
I don't find any occurence of DKIM within this repository or the documentation.
Is that intended to be supported?

**Comment by pierreozoux** [comment]
I think we can close this issue then.

If you are interested, there is this setup with opendDKIM: https://github.com/indiehosters/email ( @almereyda yes, i know you know :) )

@barryo Would you like me to add this setup in the wiki?
Would you be interested in having an official docker image?
Would you be intrested in the autoconfig?
Would you like me to open an issue for each topic? :P

Best!

Pierre

**Comment by barryo** [comment]
Hey Pierre - by all means add a page to the wiki!

**Comment by benzon** [comment]
Still think it would be a good idea with DKIM, and then print out the string that needs to be added to DNS, this way you get the feature build in, insted of having to manually create dkim, and dkim will soon be a requirement for email with the current direction of things on the internet.
