### ISSUE TITLE
Fatal error: Uncaught exception 'SmartyCompilerException'

### ISSUE THREAD

**Issue by MartH0f** [opensolutions/ViMbAdmin#98]
Hello,

I upgraded my vimbadmin installation 3.0.6 to the latest version 3.0.10 (in little steps). After the upgrade, I get the fowolling error, while I want to enter my panel:

Fatal error: Uncaught exception 'SmartyCompilerException' with message 'Syntax error in template "/srv/vimbadmin/application/views/error/error.phtml" on line 23 "<p>Please feel free to email the {mailto address=$options.identity.email encode='javascript' text=$options.identity.name}</p>" unknown tag "mailto"' in /srv/vimbadmin/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php:23 Stack trace: #0 /srv/vimbadmin/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(533): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown tag "ma...', 23) #1 /srv/vimbadmin/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2383): Smarty_Internal_TemplateCompilerBase->compileTag('mailto', Array) #2 /srv/vimbadmin/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(3093): Smarty_Internal_Templateparser->yy_r37() #3 /srv/vimbadmin/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(3191): Smarty_Internal_Templatepa in /srv/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php on line 336

I know there is another Issue with the same error, but the links that were offered, didn't worked for me. Can anybody help me?

**Comment by thiagolamosa** [comment]
Thanks for the tip, barryo.
I faced the same problem after updating from version 3.0.6 to 3.0.12.
After updating a few lines in my local application.ini (from dist version) my installation started working again.

**Comment by barryo** [comment]
:beer:
